### ISSUE TITLE
Error in my macbook

### ISSUE THREAD

**Issue by bhallacharanjit** [dokterdok/Continuity-Activation-Tool#10]
nvram: Error getting variable - 'boot-args': (iokit/common) data was not found
NOT OK. OS is protected against changes. Please reboot to automatically fix this, then relaunch the script.

This is the error. It says reboot to automatically fix but after reboot still gives the same error.

**Comment by xiaoxiaoming9** [comment]
Hello, do you have a solution to the following problem
I have been troubled for a long time, if you can get your answer, thank you very much


*Tunnelblick: macOS 10.14.5; Tunnelblick 3.7.8 (build 5180)
2019-10-13 22:36:35 *Tunnelblick: Attempting connection with client using shadow copy; Set nameserver = 769; monitoring connection
2019-10-13 22:36:35 *Tunnelblick: openvpnstart start client.tblk 52785 769 0 1 0 1065265 -ptADGNWradsgnw 2.4.6-openssl-1.0.2q
2019-10-13 22:36:50 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
*Tunnelblick: openvpnstart log:
     Loading tun-signed.kext
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. Status = 27
2019-10-13 22:36:35 *Tunnelblick: openvpnstart starting OpenVPN

**Comment by xiaoxiaoming9** [comment]
The above problems have been solved, thank you

Refer to the link
https://stackoverflow.com/questions/54631371/tunnelblick-cant-load-load-net-tunnelblick-tun-and-or-net-tunnelblick-tap-kexts
