### ISSUE TITLE
CAT hangs goes non responsive

### ISSUE THREAD

**Issue by jwilker** [dokterdok/Continuity-Activation-Tool#106]
Got my card installed, diagnostic shows OK across the board, but when I run it for installation, it pegs the CPU cores and in activity monitor it immediately after launch shows as non responsive. I've let it run for near 15 minutes to see what happens, nada.

Only thing I can think is I'm running 10.10.2...?
![screenshot 2014-12-24 15 44 18](https://cloud.githubusercontent.com/assets/527599/5551314/cc05eecc-8b83-11e4-99e1-cdebc6397e29.png)

**Comment by ebernet** [comment]
This issue is occurring with 10.0.5. Should this issue not remain open until it is resolved, either via a prompt change or fixing the issue of the spacebar not being recognized?
