### ISSUE TITLE
On mac book pro 2010 cant detect usb Asus BT400 dongle

### ISSUE THREAD

**Issue by dnbaugh** [dokterdok/Continuity-Activation-Tool#111]
My built in bluetooth seems to have bit the dust so I picked up a BT400 dongle to get bluetooth back and be able to use continuity with my iPhone via CAT.  When I try to run CAT it won't detect the dongle.  It seems to be working fine in Yosemite and shows up in the System Report.  I have been suspicious that the built in bluetooth is somehow interfering but I can't figure out how to disable it.  Please let me know if there is any way to rectify this.  Thanks

**Comment by nyrob94** [comment]
Hi there. I have an IOGEAR GBU521 BT Dongle.  Can't get CAT tool to work on my late 2009 27inch iMac. I've trial all the above. This is everything I put in the terminal:

--- Initiating Continuity mod ---

Disabling OS kext protection...         OK
Fixing disk permissions...              OK
Backing up original drivers...          Would you like to overwrite the existing backup found in /Users/..../KextsBackupBeforePatch? 
1) Yes, overwrite
2) No, skip this backup
#? 1
OK. Wi-Fi and Bluetooth kexts were backed up in '/Users/..../KextsBackupBeforePatch'
Patching blacklist........              OK
Skipping whitelist patch...             OK
Skipping old Wi-Fi driver clean up...   OK
Applying legacy Wi-Fi card patch...     OK
Verifying BT4 dongle patch status...    OK
Setting HCI switch behavior...          OK
Patching Bluetooth feature flags...     OK
Applying legacy Wi-Fi card patch...     OK
Updating kext caches...                 OK
Updating system caches...               OK
Backing up patched drivers...           Would you like to overwrite the existing backup found in /Users/...../KextsBackupAfterPatch? 
1) Yes, overwrite
2) No, skip this backup
#? 1
OK. Wi-Fi and Bluetooth kexts were backed up in '/Users/....../KextsBackupAfterPatch'

ALMOST DONE! After rebooting:
1) Make sure that both your Mac and iOS device have Bluetooth turned on, and are on the same Wi-Fi network.
2) On OS X go to SYSTEM PREFERENCES> GENERAL> and ENABLE HANDOFF.
3) On iOS go to SETTINGS> GENERAL> HANDOFF & SUGGESTED APPS> and ENABLE HANDOFF.
4) On OS X, sign out and then sign in again to your iCloud account.
Troubleshooting: support.apple.com/kb/TS5458”


-Restarted, checked system pref- didn’t work.
Ran CAT tool Option 1. did not detect dongle. Pressed any key..

“--- OS X Continuity Activation Tool 2.0.1 beta ---
                 by dokterdok                 

--- Initiating system compatibility check ---

Verifying Mac model reference...        OK
Verifying Mac board-id...               OK
Verifying OS X version...               OK
Verifying Wi-Fi hardware...             NOT OK. An Atheros AirPort card is used. An upgrade to a Broadcom one is required to make Continuity work.

Pressed any key to go back to the main menu…This however did work on my 2010 Macbook Pro. (I’m trying to get it to work on my late 2009 iMac.)

Any assistance would be greatly appreciated. Maybe this Mac just cant support it.

**Comment by dnbaugh** [comment]
Not sure what Airport card is in your iMac, but I believe I read somewhere that if it has the Atheros card it won't work, it must have the Broadcom.  It also looks like you are just running the CAT by double clicking on the app, I had to run it from command line and force the dongle installation, see post five by dokterdok.

**Comment by dokterdok** [comment]
@nyrob94 
That's correct, as stated on the homepage and in your System Diagnostic output, the Atheros Wi-Fi hardware in your iMac doesn't support Continuity. A BT4.0 USB dongle won't make Continuity work with your iMac, an [AirPort card upgrade](https://github.com/dokterdok/Continuity-Activation-Tool#airport-extreme-card-upgrades) is required.

Line to look for in your System Diagnostic output:
> Verifying Wi-Fi hardware... **NOT OK. An Atheros AirPort card is used. An upgrade to a Broadcom one is required to make Continuity work**.

Homepage [warning](https://github.com/dokterdok/Continuity-Activation-Tool#bluetooth-40-usb-dongles):

> * Atheros Wi-Fi AirPort cards will prevent Continuity from working even when adding a Bluetooth 4.0 dongle. The System Diagnostic feature of CAT tells which Wi-Fi brand is active. There are no workarounds and no patch is expected to change this, an AirPort card upgrade is required.

**Comment by nyrob94** [comment]
I tried installing the continuity activation tool on my MacBook Pro mid 2010.....it says everything its ok, installs successfully and airdrop now works but handoff doesn't. Any idea why? Im using that IOGear BT dongle.

Thanks!
Robert
