### ISSUE TITLE
Heads up that Mac mini Mid-2010 Works

### ISSUE THREAD

**Issue by nmajin** [dokterdok/Continuity-Activation-Tool#115]
Just wanted to provided a heads up that this chip (BCM94331PCIEBT4CAX) actually works in a Mid-2010 Mac mini. I looked everywhere on the interwebs for info on this and found some sites mentioning it and some sites (even this site) not mentioning it.

**Comment by dokterdok** [comment]
Thanks @nmajin for the info, did you install one yourself? Would you perhaps have a link to a guide or installation pics?
I'll update the compatibility table accordingly.

**Comment by nmajin** [comment]
It is pretty straightforward if you follow the guide at iFixit and leave jumper (J0) on the BCM94331PCIEBT4CAX unconnected and J1 and J2 connected to the antennas just like the old board.

Guide: https://www.ifixit.com/Guide/Mac+Mini+Mid+2010+AirPort-Bluetooth+Board+Replacement/6402

Since the chip is a bit different, only one screw aligns correctly:

![mac_mini_mid_2010_airport_bluetooth_board_replacement_-_ifixit](https://cloud.githubusercontent.com/assets/253669/5689435/c89d481e-9832-11e4-8897-d102c110c0d0.png)

Add some electrical tape under the new chip so it is protected from anything that might short it, and some of the antennas had to be loosened to make it fit appropriately.
