### ISSUE TITLE
Bluetooth Dongle found but not found

### ISSUE THREAD

**Issue by tarasis** [dokterdok/Continuity-Activation-Tool#116]
I was trying to use the CAT 2.0 on my Hackintosh with a GMYLE BT4.0 Dongle (based on the Broadcom chip).

When I run the System Compatability it claims that no Bluetooth Hardware is found BUT also claims that it detects BT 4.0.

![screen shot 2015-01-02 at 03 45 51](https://cloud.githubusercontent.com/assets/3006/5596092/022e93c0-9285-11e4-9ba7-3c3efd2a6ea7.png)

When I then try and install it, it fails because its waiting on seeing a Bluetooth Dongle even though there is one attached and working (my Trackpad is paired with it fine)

![screen shot 2015-01-02 at 03 47 47](https://cloud.githubusercontent.com/assets/3006/5596109/554624c4-9285-11e4-810e-509438be2ad1.png)

![screen shot 2015-01-02 at 03 47 18](https://cloud.githubusercontent.com/assets/3006/5596110/58ca3a36-9285-11e4-99ee-fbff26291985.png)

I've tried unplugging it from the USB 3 port and putting it in the USB 2 port instead, but no different.

If I press any key to continue without BT4 it fails because there is no Wifi card.

![screen shot 2015-01-02 at 03 48 13](https://cloud.githubusercontent.com/assets/3006/5596097/219e8eae-9285-11e4-89b4-e8706ebe8244.png).

Interestingly the Dongle worked just fine with the CAT 2.0 on my 13" Mid 2009 MacBook Pro. I tried it there first before trying on the Hackintosh.

I was considering attempting a forced install with  ```./Continuity\ Activation\ Tool.app/Contents/Resources/contitool.sh -f``` but wanted to see if this was a known issue.

Hardware:

GMYLE BT 4.0 Dongle
Asus Z97-A Motherboard
Intel i7-4790k
8GB Ram
NVidia GTX 970
80GB HDD for OSX
OSX 10.10.1 installed via Unibeast

Multibeast settings:

![screen shot 2015-01-02 at 13 50 43](https://cloud.githubusercontent.com/assets/3006/5596146/6882ec7e-9286-11e4-86fc-7cd570cb675d.png)

**Comment by dokterdok** [comment]
Thanks @tarasis for the detailed report. CAT has been designed for and tested with original Macs, so you might get unpredictable results when using a Hackinstosh.

Some Mac configurations have a hard time detecting dongles, this is indeed a known issue. A workaround has been identified which involves temporally disabling Bluetooth.

What I'd suggest:
* Try the workaround identified in #111
* Try using the CAT force activation feature from the command line, which skips compatibility checks. If you do that, make sure you are using [CAT 2.0.1 beta](https://github.com/dokterdok/Continuity-Activation-Tool/tree/beta) which includes bug fixes in that area.
* Look for other ways of getting Handoff to work on Hackintoshes. e.g. see [here](http://www.insanelymac.com/forum/topic/302410-patch-enabling-handoff-for-non-apple-bt4-devices/) (insanelymac.com).

As I currently have no plans to include Hackintosh support in the future, I'm closing this issue.
