### ISSUE TITLE
Not installing with a USB mouse connected

### ISSUE THREAD

**Issue by chiro79** [dokterdok/Continuity-Activation-Tool#120]
Hi,
First of all, thanks for this marvelous tool :-D

I had an issue with the CAT tool, I tried to install the version 2.0 with the .app application and it always got stuck in verifying my Mac model. Then I tried with the beta version with the same result.
After that, I tried forcing the installation, which was working until reaching the whitelist patch (patchWifiKext function in the script) where it always got stuck.
After checking the script code, I found the line in where the script stopped:
`myMacIdPattern=$($ioregPath -l | $grepPath "board-id" | $awkPath -F\" '{print $4}')`

So, I started launching each command by hand and realized that the `ioreg -l` command gets stuck when listing my mouse device (which is a Sharkoon Drakonia Black). When I disconnect it, the command runs normally, so I launched the CAT tool again, and it worked.

I let you know just in case someone else faces the same issue.

Regards.

**Comment by dokterdok** [comment]
Thanks for the report and sharing your workaround @chiro79. As this seems to be an isolated bug with the ioreg utility, I believe it's best to consider it out of CAT's scope and to recommend your workaround if other users have similar issues.
Closing.
