### ISSUE TITLE
Unable to correctly pair keyboard & trackpad with dongle after CAT

### ISSUE THREAD

**Issue by enrique89** [dokterdok/Continuity-Activation-Tool#122]
Hi,

As many have already commented, thank you to you and your community team for creating CAT. I have an early 2011 MacBook Pro 15" running 10.10.1 (Model identifier MacBookPro8,2). I purchased the Asus BT 400 bluetooth dongle based on your list of Broadcom dongles compatible with CAT. I ran CAT with no issues (after disabling internal Bluetooth first as others have mentioned!) and am successfully enjoying all the wonderful Handoff features.

Problem: However, I am unable to correctly re-pair my Apple wireless keyboard and Apple trackpad with my computer. The dongle appears to automatically pair both devices and is giving me limited functionality (I can type and move the trackpad), but no function keys on the keyboard work, and no multi-touch gestures on the trackpad work; additionally, I am unable to adjust the tracking speed. 

Another commenter mentioned having a similar problem with his mouse, and was able to fix the problem by going to System Preferences > Mouse > Set up Bluetooth Mouse. I tried that for both Keyboard and Trackpad, and did not have any luck. I tried manually turning both keyboard and trackpad off (by pressing the side buttons for a few seconds until the green light blinked off, then turning them back on). I did see the keyboard show up as able to be paired in the System Preferences > Keyboard > Set Up Bluetooth Keyboard, for a few seconds, but pressing Continue didn't do anything and then it disappeared. 

I should mention that just going to System Preferences > Bluetooth and trying to pair that way doesn't work either. Curiously, the only thing I see to pair with is my computer name, as if I could pair with what I'm assuming is the built-in Bluetooth chip. But even clicking Pair results in a failed attempt.

I spoke with an ASUS representative, and he told me they don't have any drivers or control panels that work on Mac OS, so I can't configure connected devices on that end. 

If you have any suggestions or workarounds so I can correctly pair and configure my Apple keyboard and trackpad, please let me know!

![2015-01-07 03 11 22 pm](https://cloud.githubusercontent.com/assets/10439420/5652532/78284b54-967f-11e4-9497-fc5ba2c58f49.png)

![2015-01-07 03 11 52 pm](https://cloud.githubusercontent.com/assets/10439420/5652574/d57b8e06-967f-11e4-8921-6f2f099309b0.png)

**Comment by dokterdok** [comment]
Hi @enrique89,

You might want to check out @robvanoostenrijk's [BrcmPatchRAM](https://github.com/robvanoostenrijk/BrcmPatchRAM/releases) app. It's a nifty little tool which can update your Asus USB-BT400 (amongst other Broadcom Bluetooth devices) firmware on the fly with a newer version. I've managed to successfully pair my iPhone 6 with it. I can't say if it'll solve the issue you posted but you can give a shot. 
Just make sure you go through the [readme](https://github.com/robvanoostenrijk/BrcmPatchRAM) first.

Cheers

**Comment by enrique89** [comment]
Thanks @dokterdok for your suggestions and help! I was able to properly pair & configure my peripherals by using BrcmPatchRAM and Kext Drop, as you suggested here (https://github.com/robvanoostenrijk/BrcmPatchRAM/issues/4#issuecomment-69143742). 

Closing.
