### ISSUE TITLE
OS updates

### ISSUE THREAD

**Issue by jwilker** [dokterdok/Continuity-Activation-Tool#123]
Curious, are OS updates likely to break this every time they drop, forcing us to re do everything, or are the changes not likely to be addressed in OS updates?

Specifically wondering about point releases and incremental (beta) releases.

**Comment by dokterdok** [comment]
Whenever Apple includes an updated version of the wireless drivers in an OS X update, it overwrites the previously patched drivers. Reapplying CAT is then necessary. This allows you to benefit from Continuity in addition to any improvements included in the new drivers.

Whether Apple will include wireless changes in future OS updates is anyone's guess.

**Comment by jwilker** [comment]
Cool, good to know. New Beta sitting waiting to install, will let it run and see how a second run at CAT goes :)

**Comment by jwilker** [comment]
Figured I'd add as an FYI for those running in the beta world. OS X 10.10.2 (14C94b) just installed.

Re-ran CAT, rebooted, everything was hunky dory. No logging out/in of iCloud needed. YMMV of course, but for me it all went very smoothly.

**Comment by dokterdok** [comment]
Thanks for the report jwilker.
Closing.
