### ISSUE TITLE
ASUS BT-400 and CAT 2.0.1 and iMac Early 2009 works fine

### ISSUE THREAD

**Issue by bartosz-skowronek** [dokterdok/Continuity-Activation-Tool#124]
iMac 24" Early 2009 OS X 10.10.1 + iPhone 6 (8.1.2) + Asus BT-400

1. CAT 2.0.1 downloaded
2. dongle connected
3. CAT can't recognize dongle
4. magic mouse turn off!
5. CAT can recognize dongle and runs successfully 
6. reebot 
7. iCloud sign out/in (its 23:30 and i have to go to bed!)
8. 1 night patience and Continuity works halfway (only from iPhone to Mac) 
9. sudo killall blued and sudo killall sharingd

Thanks dokterdok!

**Comment by dokterdok** [comment]
Thanks for the report @bartosz-skowronek. CAT has indeed trouble detecting dongles when accesories are paired to the internal Bluetooth, this is a known issue.
Closing.
