### ISSUE TITLE
THANK YOU TEAM! This worked perfectly for me!

### ISSUE THREAD

**Issue by mbain108** [dokterdok/Continuity-Activation-Tool#126]
This worked perfectly for me! I purchased the IOGEAR Bluetooth 4.0 USB Micro Adapter (GBU521) hopes to utilize Apple's handoff and airdrop features. I have the MacBook Pro (15-inch, Mid 2010) running OS X Yosemite. I installed 'Continuity Activation Tool'. It was seamless. There were no hiccups and all is working like a charm!

THANK YOU TEAM!

**Comment by dokterdok** [comment]
Thank you for your support @mbain108 !
