### ISSUE TITLE
No Handoff on Preferences/General after installation, MBP early 08 with Asus t400

### ISSUE THREAD

**Issue by iloverocknroll** [dokterdok/Continuity-Activation-Tool#127]
I've installed the CAT on my mac, but there's no box for activate continuity on the menu!!
Everything should look ok
![schermata 2015-01-10 alle 15 45 59](https://cloud.githubusercontent.com/assets/10476707/5691959/d1706e8c-98df-11e4-9550-8bcba407e58f.png)

Here's the menu (in italian, but you can see there's no option for enable continuity or handoff)

![schermata 2015-01-10 alle 15 47 01](https://cloud.githubusercontent.com/assets/10476707/5691961/f2fec1c0-98df-11e4-9b50-fca89fb207d0.png)

**Comment by enrique89** [comment]
Hi, if you notice on the diagnostic report the line about "Verifying AWOL status..." it says that your wifi card isn't supported. So, CAT won't work on your computer. Your only other option is to install a new wifi card, which @dokterdok mentions in the "Airport Extreme Card Upgrades" section on the main page.

**Comment by iloverocknroll** [comment]
But I got a broadcom card on my mac, 
![schermata 2015-01-10 alle 16 28 21](https://cloud.githubusercontent.com/assets/10476707/5692075/c97b2054-98e5-11e4-970b-6800b54337fa.png)

**Comment by enrique89** [comment]
Yes, you have all the right Bluetooth hardware (broadcome, etc), but Continuity/Handoff requires more than just the right Bluetooth hardware. It also requires the right Airport (wifi) card hardware, which you do not have, based on the diagnostic report you included in your first post. 

@dokterdok, correct me if I'm wrong.

**Comment by iloverocknroll** [comment]
Ok, thank you by now. I hope @dokterdok got good news for me; in the table of "compatibility, looks like mine just need the usb dongle.
I don't know it it mattes, but i receive and send, with no problems, SMS from / on my mac . That "part" of handoff works, and always worked :)

**Comment by dokterdok** [comment]
Hello,
@enrique89 is correct, your AirPort Extreme card is not compatible with CAT.
@iloverocknroll SMS and calling don't need CAT to work - CAT has no influence on those features. 
Early 2008 MacBook Pros are in the red zone on the chart, you misunderstood I'm afraid: no AirPort Extreme upgrade options are known today for that Mac model : no one has reported a successful upgrade so far.

**Comment by iloverocknroll** [comment]
Thank you @dokterdok
To be honest I installed cat for call and receive calls on my Mac; do you know if it is possible or it need "extended" handoff given by cat?

**Comment by dokterdok** [comment]
CAT won't help you with Continuity calling as far as I know. To troubleshoot that feature, I'd suggest you look at other sites (e.g. [here](http://www.igeeksblog.com/continuity-calling-not-working-in-ios-8/)) that will better help you.

**Comment by iloverocknroll** [comment]
@dokterdok I've unistalled CAT but now EVERY time I need to configurate my mac to send and receive SMS!!
