### ISSUE TITLE
GMYLE iMac 2011

### ISSUE THREAD

**Issue by ageorgios** [dokterdok/Continuity-Activation-Tool#128]
Hello I have bought GMULE BT 4.0 Dual-mode but the tool will not recognize it when inserted in the USB Slot. Does anybody have exact procedure?

Thank you

![screen shot 2015-01-13 at 18 44 43](https://cloud.githubusercontent.com/assets/3126351/5724460/570f8124-9b54-11e4-8ebf-b4cece69f084.png)

**Comment by ageorgios** [comment]
I think the problem is that I have Atheros based Wifi, is that true?

**Comment by dokterdok** [comment]
Hello,
Open CAT and run the system diagnostic. If you see a "NOT OK", then it will tell you what's wrong (e.g Atheros Wi-Fi cards don't work with Continuity).
The homepage also contains important compatibility/troubleshooting info, please make sure you read it.
