### ISSUE TITLE
Version 2.0 fails to activate Asus BT400 dongle on iMac mid 2011

### ISSUE THREAD

**Issue by SteffenB70** [dokterdok/Continuity-Activation-Tool#130]
Unfortunately, the activation tool remains stuck during the activation process, suggesting to plug in the dongle (which I did several times) or to continue without activating the dongle... I'm running 10.10.2 latest public beta - perhaps that causes the issue? (Otherwise, the dongle is listed in the system report under USB)

**Comment by dokterdok** [comment]
Hello, this is a known issue with workarounds. This is likely related to one or more paired Bluetooth accesories that keep the internal Bluetooth controller active, which confuses CAT's dongle detection routine.

Could you please try this:

1. Plug your dongle in and Activate with [CAT 2.0.1 beta](https://github.com/dokterdok/Continuity-Activation-Tool/tree/beta)
2. When the prompt is displayed, turn Bluetooth off (System Preferences>Bluetooth>Turn Bluetooth off)
3. Wait until the end of the activation procedure before turning Bluetooth back on

You might need to re-pair your devices after the reboot. If you run into issues with pairing, refer to issue #122.

**Comment by SteffenB70** [comment]
Hi David,

First many thanks for the efforts. Thanks also for the quick reply.

Unfortunately, I couldn't locate the link to 2.0.1 on the main page (it's mentioned but the download link below is still for 2.0.0?). I also don't know for sure how I can steer the iMac after switching off Bluetooth (since both keyboard and mouse are BT connected to it...)? Should I need wired keyboard and mouse for the procedure?

Thanks again, best wishes from Heidelberg,

Steffen

**Comment by dokterdok** [comment]
Hi Steffen,

You can also try to force the activation by using the command line activation and therefore you won't need to turnoff Bluetooth. Here' the [direct link](https://github.com/dokterdok/Continuity-Activation-Tool/archive/beta.zip) to download v.2.0.1. 

Then follow these steps:

1. Copy the app on your desktop
2. Open Terminal
3. Type ```cd "$HOME/Desktop/Continuity Activation Tool.app/Contents/Resources"```
4. Type ```sudo ./contitool.sh -f```

**Comment by SteffenB70** [comment]
Hi David,

Thanks. I ran the commands as suggested. It seemed to work, reporting everything as ok but after the restart the system reports still claims that all continuity features are inactive... maybe I wait a bit?

**Comment by dokterdok** [comment]
Steffen,
Have you tried to unplug / replug the dongle after the reboot?
If that doesn't work, then please copy/paste a CAT System Diagnostic output here.

**Comment by SteffenB70** [comment]
David,

Indeed unplugging / replugging the dongle appears to activate the dongle after the reboot. But maybe I'm too silly for this... my BT bluetooth and BT mouse lost connections and I wouldn't know how to re-pair them (since I've lost any means to manipulate the iMac and there also didn't seem to be an auto-routine by the iMac to start looking for devices)...

**Comment by SteffenB70** [comment]
Hi David,

Please find below the CAT report. Thanks!

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: iMac12,2
Verifying Mac board-id...               OK. Long board id detected: Mac-942B59F58194171B
Verifying OS X version...               OK. Mac OS X 10.10.2 (14C106a) detected
Verifying Wi-Fi hardware...             NOT OK. An Atheros AirPort card is used, Continuity will not work. An upgrade to a compatible Broadcom card is necessary.
Verifying AWDL status...                NOT OK. Your Wi-Fi card doesn't support AWDL, and therefore doesn't work with Continuity.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in

**Comment by dokterdok** [comment]
I'm afraid the Wi-Fi card in your iMac doesn't support Continuity unfortunately:

> Verifying Wi-Fi hardware... NOT OK. An Atheros AirPort card is used, Continuity will not work. An upgrade to a compatible Broadcom card is necessary.
> Verifying AWDL status... NOT OK. Your Wi-Fi card doesn't support AWDL, and therefore doesn't work with Continuity.

As described on the homepage:
> Atheros Wi-Fi AirPort cards will prevent Continuity from working even when adding a Bluetooth 4.0 dongle. The System Diagnostic feature of CAT tells which Wi-Fi brand is active. There are no workarounds and no patch is expected to change this, an AirPort card upgrade is required
I'd recommend you uninstall CAT and look through the options on the main site

The only option is to upgrade the internal Wi-Fi card, you can find the correct model in the [compatibility table](https://github.com/dokterdok/Continuity-Activation-Tool#airport-extreme-card-upgrades). If you're interested, you can find more info on the procedure in issue #46. Good luck!

**Comment by SteffenB70** [comment]
Thanks for all your efforts David.

I looked up issue #46 but I'm not sure whether I can follow all the details in this discussion.

**Comment by dokterdok** [comment]
Yes the installation appears to be quite technical on an iMac, there might be other step by step guides out there (e.g. [here](https://www.ifixit.com/Guide/iMac+Intel+27-Inch+EMC+2429+AirPort+Card+Replacement/7552)). However, I wouldn't recommend doing it if you're not familiar with internal hardware upgrades... 

Cheers, closing.
.

**Comment by SteffenB70** [comment]
Thanks David!
