### ISSUE TITLE
USB dongle doesn't run with ver 2.0.0

### ISSUE THREAD

**Issue by byvlad** [dokterdok/Continuity-Activation-Tool#137]
Hi! Macbook pro early 2011, usb dongle Grand-X Bluetooth 4.0 (BT40G) doesn't run with continuity tool 2.0.0, but running with version 1.0.0, but... after one day computer forget about activation(
what are you recommend me to do?

**Comment by dokterdok** [comment]
Hello, this seems to be a duplicate of issue #130. Also make sure you have a Broadcom based BT dongle, other brands are not supported (see homepage - all the info you need should be there).
Closing.
