### ISSUE TITLE
OS X 10.10.2 Breaks Handoff

### ISSUE THREAD

**Issue by nmajin** [dokterdok/Continuity-Activation-Tool#140]
Doesn't even have the checkbox anymore under General for enabling Handoff

**Comment by jwilker** [comment]
just looked at my machine. its there on mine. it won't be there if its not supported though,

**Comment by nmajin** [comment]
Hmm. I've had it working perfectly until I just updated, even ran the tool again and no luck.

**Comment by nmajin** [comment]
After a reboot it's there but still not working.

**Comment by nmajin** [comment]
Well I'm seeing some weird behavior lol or I must be drunk :P Anyway, keep an eye out with this update.

**Comment by jwilker** [comment]
Weird. I know for me after os updates it takes a few minutes for everything to start working again.
