### ISSUE TITLE
Will this work after updating to OS X 10.10.2??

### ISSUE THREAD

**Issue by mdwoolweaver** [dokterdok/Continuity-Activation-Tool#142]
I was wondering if the would still work after updating to OS X 10.10.2? As i just got it all working nicely and don't wanna lose it

**Comment by jwilker** [comment]
Worked fine for me. Just re-run CAT after the OS Update.

For me: 2011 MBP. I went in and replaced my BT/Wifi card. 

That said though, I've been on OS X betas and have had no issues on any of the releases re-activating via CAT
