### ISSUE TITLE
Bluetooth dongle not detected in CAT

### ISSUE THREAD

**Issue by dlonly** [dokterdok/Continuity-Activation-Tool#145]
Hi !

First of all thanks for all the work.

I try to use CAT on my MacBook Pro 15" late 2008 with GYMLE USB dongle.

This dongle with seems to work properly according to the official dongle chart. 

http://www.amazon.fr/gp/product/B007MKMJGO?psc=1&redirect=true&ref_=oh_aui_detailpage_o02_s00

The dongle work fine on the MacBook but CAT can't find it. I tried to install CAT without dongle support but of course I can't activate Continuity in preference.

What should I do?

Thanks.

**Comment by dokterdok** [comment]
Hello,
This is a known issue. To summarize, there are three different workarounds (choose one of them):

* Turn off Bluetooth accessories then unplug / re-plug the dongle before running CAT
* Turn off Bluetooth then unplug / re-plug the dongle before running CAT
* Force the activation using the terminal

Please have a look at the steps described in #130 for more context.
