### ISSUE TITLE
Bluetooth fails on OS X 10.10.2

### ISSUE THREAD

**Issue by spbriggs** [dokterdok/Continuity-Activation-Tool#146]
I had this working with Yosemite 10.10.1 but lost Continuity with the update to 10.10.2

I have a MacBook Pro mid 2010 15" retrofitted with BCM94331PCIEBT4CAX card

I've done a restore from Recovery disk (with the -r option) and am left without functioning wifi but with working Bluetooth.

On running CAT compatibility check I get

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro6,2
Verifying Mac board-id...               OK. Short board id detected: Mac-F22586C8
Verifying OS X version...               OK. Mac OS X 10.10.2 (14C109) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and uses the legacy Brcm4331 kext. This tool can fix this.
Verifying AWDL status...                OK. No AWDL is active, but the hardware seems to be able to support it. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v147 c5799

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Warning: Blacklist not found in the Bluetooth drivers. An OS X update might have made this hack useless.
                                           However, your Mac model shouldn't need to be removed from that blacklist.
Verifying Wi-Fi whitelist status...     NOT OK. No whitelist detected in the Wi-Fi drivers, this tool won't be able to patch it
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
Verifying BT4 dongles compatibility...  WARNING. Unpatchable drivers found. They are either already patched or don't support CAT.

Installation refuses to proceed.

**Comment by dokterdok** [comment]
Please see #139 which describes in detail what to do when an OS X update comes out. The best thing to do is just re-activate with CAT in case you lost Continuity.

In short: my understanding is that that you overwrote the new OS X 10.10.2 drivers with old ones from the recovery disk, that are incompatible with OS X 10.10.2. OS X updates don't necessarily update what's on your recovery disk apparently. The "-r" recovery option should therefore be used with care.

An immediate workaround in your case: 

0. Download and install [Kext Drop](http://www.cindori.org/software/kextdrop/).
1. Go to your user directory>KextBackAfterPatch. The patched OS X 10.10.1 kexts should be in there. Better yet : get a clean copy of the OS X 10.10.2 IO80211Family.kext.
2. Open Kext Drop, drag and drop the IO80211Family.kext into the window. Click Install.
3. Reboot, verify if your Wi-Fi connectivity is back.
4. Re-activate with CAT.

**Comment by spbriggs** [comment]
Thanks for the pointers. I've reinstalled the OS 10.10.2 update from Apple and ran CAT again. All working perfectly now.

Thank you.
