### ISSUE TITLE
Mid-2014 MBP Retina running OS X 10.9.5 fails, version "too old"

### ISSUE THREAD

**Issue by JimmyNootron** [dokterdok/Continuity-Activation-Tool#154]
My enterprise is preventing upgrade to Yosemite, and I'm stuck on 10.9.5 with a brand-new 15" MBP Retina. When I run the activation tool, it fails when verifying OS X version: "NOT OK. Your OS X version is too old to work with this hack. Aborting."

Unfortunately, I'm also a Mac newbie. Any suggestions?

**Comment by jeroenvankeulen85** [comment]
Get the enterprice IT dude and threaten to hang him by a string of he doesn't give you Yosemite. After he does it for you, you do not need the activation tool. Your mac is capable of doing all these great things by it self! Good luck

**Comment by jeroenvankeulen85** [comment]
To be compleet: Airdrop OSX and iOS is a new feature in Yosemite so is Handoff. These features a Yosemite only.

**Comment by JimmyNootron** [comment]
Yep, I know all problems are solved by upgrading to Yosemite ;) Actually I even did the upgrade, confirmed it all worked, but then realized I broke McAfee security, which I cannot update because it's remotely administered. So I had to restore the previous OS via Time Machine.

Now I'm just trying to get the phone integration (call alerts, click-to-call, etc.) and Handoff functionality. The way I understand it, that's what this hack does. I just don't understand why it's seeing OS X 10.9 as "too old"...

**Comment by JimmyNootron** [comment]
Oh, wait. Starting to think this hack bridges the hardware gap only...still requires Yosemite. Works great for old hardware running new software, but not the other way around. Is that it? No way to get the phone integration on Mavericks then?

**Comment by jeroenvankeulen85** [comment]
The features you want are yosemite features only! CAT was designed to make Mac's running yosemite with a new bt 4.0 airport card or BT 4.0 dongle use these new features. All these new features require BT 4.0. Basically CAT Tells to your Mac that you use a BT 4.0 dongle or card. As default your MBP already has this hardware, and does not need this hack. On this moment there is no way known to get these features to older OS X Versions.

**Comment by jeroenvankeulen85** [comment]
When OS X Yosemite is installing it reads your Hardware info, even MBA 2011 with OEM BT 4.0 card where not Handoff / Continuity / Airdrop iOSand OSX supported. 

This hack tells Yosemite to enable the features when you have a BT 4.0 card or dongle installed.

**Comment by JimmyNootron** [comment]
Yeah, what I was afraid of. Oh, well. Thanks for confirming!
