### ISSUE TITLE
CAT successfully installs, but no inbound calls or SMS

### ISSUE THREAD

**Issue by sstillwell** [dokterdok/Continuity-Activation-Tool#157]
CAT 2.0, Mac Pro mid 2012 quad-core (MacPro5,1) with IOGEAR GBU521 dongle and OS X 10.10.2.  iPhone 6 Plus 64GB with iOS 8.1.3.  CAT installed with no problems, and diagnostics shows:

```
--- OS X Continuity Activation Tool 2.0.0 ---
                 by dokterdok                 

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacPro5,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F221BEC8
Verifying OS X version...               OK. Mac OS X 10.10.2 (14C109) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is not active. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.
Verifying BT4 dongles compatibility...  OK. The patch that enables BT4 USB dongles compatibility has already been applied
```
Bluetooth is on in OS X Preferences and on the iPhone, iPhone is not paired to the Mac.
Have logged out of iCloud on ALL devices, rebooted and/or shut down and logged back in, Mac Pro first.
iPhone Cellular Calls is enabled in FaceTime prefs on the iPhone and on the Mac.
Keychain is enabled.
Preferences > General > Allow Handoff between this Mac and your iCloud devices is present and enabled.
B

What's weird is that OUTBOUND calling from FaceTime using the iPhone works.  I just never get any inbound notification.
Also weird - on the phone in Preferences > Messages > Text message Forwarding, I do not see this Mac listed, although my MacBook Pro (which shouldn't be supported for this) and my iPad Air 2 both do.

So close...yet so far away.  If there's any other information I can provide, just let me know.

**Comment by Walril** [comment]
To be honest, the phone call feature works via wifi not bluetooth. So I don't think the tool is your issue. Only bluetooth uses in continuity is for handoff

**Comment by sstillwell** [comment]
I'm not sure what's going on - I've got two other machines that aren't SUPPOSED to support it (a late-2011 MacBook Pro and a mid-2011 Mac Mini) that are working fine out of the box with no changes at all, as well as an iPad 2 - it's almost as frustrating to see those work as it is to see the other NOT work, because of course the one that I NEED to have work is the one that doesn't.  Murphy's law strikes again. :(  If anyone has suggestions on where to look I'd be thankful - I was working with Apple support until after 3:00 this morning trying to figure it out.

**Comment by Walril** [comment]
Well I believe the only requirements for the calling feature is iOS 8,
Yosemite, and the same WiFi network.

On Mon, Mar 9, 2015 at 10:05 AM, sstillwell <notifications@github.com>
wrote:

> I'm not sure what's going on - I've got two other machines that aren't
> SUPPOSED to support it (a late-2011 MacBook Pro and a mid-2011 Mac Mini)
> that are working fine out of the box with no changes at all, as well as an
> iPad 2 - it's almost as frustrating to see those work as it is to see the
> other NOT work, because of course the one that I NEED to have work is the
> one that doesn't. Murphy's law strikes again. :( If anyone has suggestions
> on where to look I'd be thankful - I was working with Apple support until
> after 3:00 this morning trying to figure it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokterdok/Continuity-Activation-Tool/issues/157#issuecomment-77858924>
> .
>



-- 

Walter Hardeman

**Comment by sstillwell** [comment]
Right, I understand that - but Apple will still tell you that it's not supported except on a specific list of machines that doesn't include any of the ones I'm using except for a new iPad Air 2. Still trying to figure out what's special about this one Mac Pro that makes it NOT work.  Probably not appropriate as a GitHub issue - I'll try to find a forum to take the problem to.  Thanks.

**Comment by sstillwell** [comment]
Followup for completeness' sake - while on the phone with Apple Support, the Mac Pro started working with Text Forwarding and iPhone Cellular Calls as mysteriously as it failed to in the first place.  No clue why it started working.  CAT isn't even active on the machine now.  My primary use case is for SMS and calls, not the other Continuity features, so I don't know if I'll risk breaking things by reinstalling it.  FYI and FWIW.
