### ISSUE TITLE
Macbook Pro Mid 2010

### ISSUE THREAD

**Issue by nyrob94** [dokterdok/Continuity-Activation-Tool#164]
I tried installing the continuity activation tool on my MacBook Pro mid 2010.....it says everything its ok, installs successfully and airdrop now along with Handoff work. I just cant get MacID to work. Any idea why?

Thanks!
Robert

**Comment by dokterdok** [comment]
Hi Robert,
This is a known issue with no known workaround, sorry.
Closing (duplicate of #135)
