### ISSUE TITLE
Handoff / Airdrop (one way, iPhone to OS X) not working

### ISSUE THREAD

**Issue by jasowt** [dokterdok/Continuity-Activation-Tool#169]
Hi,

After several installs, uninstalls and reinstalls, and many signings in and out of iCloud on my iPhone and MacBook Pro (13-inch, Early 2011), I cannot get Handoff / Airdrop (from iPhone to OS X) to work. Airdrop from OS X to iPhone does sporadically work.
I'm using a GYMLE Enhanced Range Bluetooth dongle.
I'm on iOS 8.3 and OS X 10.10.3.

I've tried all suggestions so far that I've read about turning various different settings on and off. Nothing works. One suggestion I read on http://forums.macrumors.com/showthread.php?t=1793957&page=3 included the step "5) On your mac, delete 2 files in ~/Library/Preferences. com.apple.sharingd.plist, and com.apple.ids.deviceproperties.plist. Also open keychain access and search for handoff. Delete the encryption key." 

There was no com.apple.ids.deviceproperties.plist or encryption key in Keychain Access.

I've attached the System Diagnostic Report below.

Any help would be hugely appreciated!

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,1
Verifying Mac board-id...               OK. Long board id detected: Mac-94245B3640C91C81
Verifying OS X version...               OK. Mac OS X 10.10.3 (14D131) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=4, expected 6.
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v42 c847

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is not active. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.
Verifying BT4 dongles compatibility...  OK. The patch that enables BT4 USB dongles compatibility has already been applied

**Comment by dokterdok** [comment]
Hi, 
I'm afraid it won't work. According to [Amazon](http://www.amazon.com/GMYLE-Ultra-Mini-Bluetooth-Wireless-Adapter/dp/B00F85ZPIY) this version of the the dongle is using a CSR chipset, which is not compatible with CAT. I will update the home page to avoid confusion.

Your best bet is to find a compatible Broadcom Bluetooth 4.0 USB adapter or to upgrade the AirPort Extreme card.
