### ISSUE TITLE
sudo needed?

### ISSUE THREAD

**Issue by CaptSaltyJack** [dokterdok/Continuity-Activation-Tool#170]
Do I have to use `sudo` to run the script? If I run it without, I get errors that are permissions related. It doesn't seem to use `sudo` on its own.

**Comment by dokterdok** [comment]
Yes the app needs sudo to run the Activation and Uninstallation features.
The System Diagnostic feature doesn't need sudo. Use the latest [beta 2.0.1](https://github.com/dokterdok/Continuity-Activation-Tool/tree/beta) if you run the tool from the command line, it includes fixes in that area.
