### ISSUE TITLE
Nothing Happens on Mac Pro Early 2009

### ISSUE THREAD

**Issue by robinsonsampa** [dokterdok/Continuity-Activation-Tool#171]
Hi, I have a Mac Pro 2009 with 10.10.3 and a ASUS BT400. To be sure internal Bluetooth will not conflict with that, I unplugged the cable from the internal BT.

I tried the master and the beta and when I do a System Diagnostic it says:

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacPro4,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F221BEC8
Verifying OS X version...               OK. Mac OS X 10.10.3 (14D131) detected
Verifying Wi-Fi hardware...             NOT OK. No active AirPort card was detected. Continuity will not work.
Verifying AWDL status...                NOT OK. Your Wi-Fi card doesn't support AWDL, and therefore doesn't work with Continuity.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
"Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in"  <---- THIS LINE SAYS IT CAN ENABLE IT

But every time I try to Activate, I got this error:

--- OS X Continuity Activation Tool 2.0.1 beta ---
                 by dokterdok                 

--- Initiating system compatibility check ---

Verifying Mac model reference...        OK
Verifying Mac board-id...               OK
Verifying OS X version...               OK
Verifying Wi-Fi hardware...             NOT OK. No active AirPort card was detected. Continuity will not work. Aborting.

Press any key to go back to the main menu...

So it stops and nothing changes. What can I do?

Thank you!

**Comment by robinsonsampa** [comment]
I tried to force installation using -f, and unplug/replug the dongle on many different port. Nothing changes.
The bluetooth is working ok, here is the System Information:

 Apple Bluetooth Software Version:	4.3.4f4 15601
  Hardware, Features, and Settings:
  Name:	Robinson
  Address:	5C-F3-70-67-18-C6
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	No
  Instant Hotspot Supported:	No
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	20702A3
  Firmware Version:	v14 c4096
  Bluetooth Power:	On
  Discoverable:	Off
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0B05
  Product ID:	0x17CB
  HCI Version:	0x6
  HCI Revision:	0x1000
  LMP Version:	0x6
  LMP Subversion:	0x220E
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Desktop
  Composite Class Of Device:	0x380104
  Device Class (Major):	0x01
  Device Class (Minor):	0x01
  Service Class:	0x1C0
  Auto Seek Keyboard:	On

Tks.

**Comment by dokterdok** [comment]
The issue is with your Wi-Fi. Continuity works with a combination of Wi-Fi and Bluetooth, so just having compatible Bluetooth hardware won't cut it. Make sure you have compatible Broadcom based Wi-Fi hardware and you should be good to go.
