### ISSUE TITLE
No Connectivity options in Mac pref's

### ISSUE THREAD

**Issue by PlaceboAddy** [dokterdok/Continuity-Activation-Tool#176]
Mac Mini / 2.53ghz / 8gig RAM / 512gig SD

I followed the steps, turned off iCloud, messing things up, turned off bluetooth stuff, installed, restarted, yadda, yadda, yadda, and nothing.

No Connectivity option in "general" preferences on Mac - no "CLEAR" options on how to correct when this happens.  I've seen other posts regarding caring out some "sudo kextcache" or something, but I can't find them (not in mine?) and not real clear what to do anyway.

Had hoped with the app this would be an easy double click install option and was ready and willing to "DONATE".  I'm not lazy - just not "terminal" savvy and not a coder.  So no Airdrop for me and no donate.   :-(

**Comment by dokterdok** [comment]
Hi PlaceboAddy,
Could you please copy/paste the CAT System Diagnostic? It looks like Continuity was not activated.

**Comment by PlaceboAddy** [comment]
None to paste I guess?  Didn't run a diagnostic.  I installed (activated)  then uninstalled after it didn't work.

When I did run a diagnostic afterwaeds - seemed dumb - telling me even tho I have a qualifying mac - it said my airport card (apple) wouldn't work.

Seemed all buggy

**Comment by dokterdok** [comment]
We need more info in order to help.
Could you open the CAT utility, run the system diagnostic, and post what's displayed here?
Thanks

**Comment by PlaceboAddy** [comment]
Also, current OS 10.10.3   (this was installed before I started trying to use the continuity tool)

The following information is AFTER I tried installing, uninstalling and reinstalling unsuccessfully, so the did a final Uninstall.  All the information below seems to imply everything should have went off without a hitch, but no, it did not. I saw another post in regards to this giving steps involving a couple of restarts and removing files from one of the presence folders, library folders. 


INFO FROM CONTINUITY TOOL______________________________________

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: Macmini3,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F22C86C8
Verifying OS X version...               OK. Mac OS X 10.10.3 (14D136) detected
Verifying Wi-Fi hardware...             OK. AirPort driver com.apple.driver.AirPortBrcm43224 was detected. The tool will try to fix this.
Verifying AWDL status...                NOT OK. Your Wi-Fi card doesn't support AWDL, and therefore doesn't work with Continuity.
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=4, expected 6.
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v208 c521

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in

Press any key to go back to the main menu...

**Comment by dokterdok** [comment]
If you see a NOT OK in the system diagnostic, then something is currently wrong with your system that CAT likely can't fix.

*Verifying Bluetooth version... NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity.*

It seems your Mac doesn't have a compatible Bluetooth 4.0 USB dongle attached. Is that correct? This is required for your MacMini model. Have a look at the [home page](https://github.com/dokterdok/Continuity-Activation-Tool) for compatible dongles.

**Comment by PlaceboAddy** [comment]
Yes, it DOES have a compatible 4.0 bluetooth, in fact - one of which you have listed somewhere as one of the best, or one tested Asus with broadband.  I just didn't start up with the 4.0 dongle.  (I'll do it again and repost diagnostics)

And if my Mac Mini isn't compatible with wifi - then you should remove Mac Mini (late 2009) from your lists.
Otherwise ... after I ran your app for continuity - the listing for wifi marked off as "ok" - EVEN after what is shows in diagnostics 

Further - your own diagnostics on the wifi say the following:
* Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
* Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.

**Comment by PlaceboAddy** [comment]
Also checking my Mini's wifi information:

Card Type:	AirPort Extreme  (0x14E4, 0x90)
  Firmware Version:	Broadcom BCM43xx 1.0 (5.10.131.36.16)
  MAC Address:	90:84:0d:f3:de:08
  Locale:	FCC
  Country Code:	US
  Supported PHY Modes:	802.11 a/b/g/n
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 149, 153, 157, 161, 165
  Wake On Wireless:	Supported
  Status:	Connected

**Comment by PlaceboAddy** [comment]
I just went through the process of turning off bluetooth, plugging in the 4.0 dongle, and just reinstalled.  Diagnostics test is now showing incompatible wifi/.  I don't know how that's possible??

Here is the information:

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: Macmini3,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F22C86C8
Verifying OS X version...               OK. Mac OS X 10.10.3 (14D136) detected
Verifying Wi-Fi hardware...             OK. AirPort driver com.apple.driver.AirPortBrcm43224 was detected. The tool will try to fix this.
Verifying AWDL status...                NOT OK. Your Wi-Fi card doesn't support AWDL, and therefore doesn't work with Continuity.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.
Verifying BT4 dongles compatibility...  OK. The patch that enables BT4 USB dongles compatibility has already been applied

**Comment by PlaceboAddy** [comment]
FYI:  During this attempt I have not signed out /in of my cloud as I didn't think it a necessary step yet since hardware wasn't passing?

So... what do I have to do?  I already bought a dongle.  I have to purchase a new Apple wifi card for our Mini that already has an Apple wifi card?

**Comment by PlaceboAddy** [comment]
apparently I'm S out of luck!
