### ISSUE TITLE
Compatibility List for Wifi - incorrect ??

### ISSUE THREAD

**Issue by PlaceboAddy** [dokterdok/Continuity-Activation-Tool#178]
Apparently ... I'm TWO for TWO = ZERO

My Mac Mini 2009 listed on the compatibility list as being ABLE to work with a BT 4.0 dongle didn't work.  That problem and item went to the way side.
https://github.com/dokterdok/Continuity-Activation-Tool/issues/176#issuecomment-99753266

And now... with a iMac i7 (mid 2011) OS X.X.3 with an Atheros WiFi chip Airport card, which SPECIFICALLY says on the compatibility list as "works with new airport extreme card" (Atheros) 
...... after I ran the system diagnosis - it ALSO says "NOT OK."  Your wi-fi card doesn't support AWDL, and therefore doesn't work with Continuity.  

>>SAME<< issue as with my Mini ! 
So what gives?  It seems there's more than just my wifi cards not working / being compatible here.  Two for two ??  C"mon?

**Comment by PlaceboAddy** [comment]
WOW!  In looking more through some of the issues, it seems there's an issue with 10.10.3 and the Continuity Activation tool !!  People talk about it getting broke - I'm dealing after I've already had it installed a long time. 

And now... more and more.. I see people soldering new bluetooth cards, or wifi cards into their iMacs, having to buy used $40 wifi cards to stick in their Mini's - JUST to have continuity!!  Am I mistaken??

I just wanted to be able to quickly and wirelessly swap files between desktop to desktop and iOS devices, but not at the cost and time of buying more hardware, swapping out parts.  HECK.... even my mid 2011 iMac still has AppleCare left on it!  Pull the thing apart to swap out a perfectly good wifi card to have continuity?  WHY??

Maybe had the tool worked in the first place?  Tell me though... what benefit this is and why go through the hardware hassle and headache?

**Comment by PlaceboAddy** [comment]
************  THINK TWICE BEFORE ATTEMPTING THIS THING !!! ************

Along with my only other post (that I closed because of no replies)  I guess I'm *SOL* ??

After trying this,  what now appears to be an abandoned beta application project - and using Safari's recent 8.0.6 update -  my system is somewhat screwed up.  

Safari certainly doesn't work.  I tried several things on my own, and then spent over an hour with Apple Tier 2 tech support, shredding down Safari and other components naked - and it still doesn't work, which indicates something else is screwed up in my system.  WHO KNOWS?!?!

SO... I guess I'll be going back through a week's worth of work after HAVING to restore from Time Machine because of this thing.  WHO KNEW this would crash other components besides USB ?!?  

After un-installing - there was no indication, no warning of anything else breaking.
SO THINK TWICE BEFORE ATTEMPTING this thing, and check if it's EVEN something you want to bother with!!  I never got an answer as to if why I should, and what benefit there "might" be from this.

**Comment by dokterdok** [comment]
@PlaceboAddy Thanks for those reports, I'm sorry to hear you're having a bad experience with the tool. 

This app was released in its AS IS state with no guarantee that it will work. [Warnings](https://github.com/dokterdok/Continuity-Activation-Tool#warning) are stated on the homepage for a reason: things can indeed go wrong.

Following the [troubleshooting guidelines](https://github.com/dokterdok/Continuity-Activation-Tool#troubleshooting) is the best way to get help from CAT's community. The Issues Section of this Github project is not the right venue for opinion based discussions, double-posts or rudeness. Closing.
