### ISSUE TITLE
Killed the Radio

### ISSUE THREAD

**Issue by RoadKhil** [dokterdok/Continuity-Activation-Tool#180]
************  THINK TWICE BEFORE ATTEMPTING THIS THING !!! ************
************  THINK TWICE BEFORE ATTEMPTING THIS THING !!! ************
Be sure and check if this is EVEN something viable you want to  bother with!! 

I feel this is a valid warning since I've posted a couple times with no help or response before things went sideways with no luck.  I guess I'm *SOL* ?! 

It seems it's been several months since any updates on this project and since OS 10.3.3 came out and possibly made this tool and option obsolete?  Who knows - because there's no updates or responses.  I see others who have succeeded, but those are older posts, and I can only speak for my own experience.

After trying this,  what now appears to be an abandoned beta application project - and then using Safari's recent 8.0.6 update (March 8)  my system is somewhat screwed up.  Safari certainly doesn't work!  And I haven't had time to check in-depth.

To fix Safari - I tried several things on my own, and then spent over an hour with Apple Tier 2 tech support, shredding down Safari and other components, naked - and it still doesn't work, which indicates something else is screwed up in my system.  WHO KNOWS?!?!

After un-installing the activation tool - there was no overt indication, no warning of anything else breaking.
SO THINK TWICE BEFORE ATTEMPTING this thing.  I NEVER got an answer - so be sure to check if this is EVEN something viable you want to  bother with!! 

So I guess I'll be going back through a week's worth of work after HAVING to restore from Time Machine because of this thing.  WHO KNEW this would crash other components besides USB ?!?  

************  THINK TWICE BEFORE ATTEMPTING THIS THING !!! ************
************  THINK TWICE BEFORE ATTEMPTING THIS THING !!! ************

**Comment by dokterdok** [comment]
Double post. #178. Closing.
