### ISSUE TITLE
compatibilty Macbook pro 5,3 mid 2009

### ISSUE THREAD

**Issue by OgniSre** [dokterdok/Continuity-Activation-Tool#188]
not clear which card to use or only dongel? Please help.

**Comment by jeroenvankeulen85** [comment]
It should work with a BT4.0 dongle 

http://www.ebay.com/itm/Dual-Mode-Bluetooth-4-0-Micro-USB-Dongle-Low-Energy-Broadcom-BCM20702-Adapter-/301333201181?pt=LH_DefaultDomain_0&hash=item4628dbc11d

Good luck!

**Comment by OgniSre** [comment]
thanks for your quick answer!
However, I would prefer to replace the card in my macbook. Any chance and which? Thanks again...

**Comment by jeroenvankeulen85** [comment]
No, that will be impossible. 
Sorry
