### ISSUE TITLE
Continuity-Activation-Tool gives warnings at Mac OS X 10.11. El Capitan public Beta

### ISSUE THREAD

**Issue by Roedelproemm** [dokterdok/Continuity-Activation-Tool#193]
Maybe it didn't work anymore. I tried only the system Diagnostic mode. The tool works great under OS X 10.10. and all it's beta versions.

Sincerely

Thomas
--- OS X Continuity Activation Tool 2.0.0 ---
                 by dokterdok                 

Select an option:

1) Activate Continuity  3) Uninstall
2) System Diagnostic    4) Quit
# ? 2

--- OS X Continuity Activation Tool 2.0.0 ---
                 by dokterdok                 

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,1
Verifying Mac board-id...               OK. Long board id detected: Mac-94245B3640C91C81
Verifying OS X version...               Warning: This tool wasn't tested with OS X versions higher than 10.10. Detected OS version: 10.11
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and uses the legacy Brcm4331 kext. This tool can fix this.
Verifying AWDL status...                OK. No AWDL is active, but the hardware seems to be able to support it. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          /Users/Thomas/Downloads/Continuity-Activation-Tool-master-2/Continuity Activation Tool.app/Contents/Resources/contitool.sh: line 357: [: 6
6: integer expression expected
NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=6
6, expected 6.
Verifying Bluetooth features...         WARNING. Unknown Bluetooth features have been detected (code:15
15). This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v151 c5844

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Warning: Blacklist not found in the Bluetooth drivers. An OS X update might have made this hack useless.
                                           However, your Mac model shouldn't need to be removed from that blacklist.
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
Verifying BT4 dongles compatibility...  WARNING. Unpatchable drivers found. They are either already patched or don't support CAT.

Press any key to go back to the main menu...

**Comment by crypiehef** [comment]
I can confirm I am receiving the exact same error. Worked great in Yosemite but getting the integer error as well. I will try to edit the .sh file in the container to see if I can get it working and report back.

**Comment by crypiehef** [comment]
Ok, I ran the contitool.sh script manually with the -f flag to run without checks (as I know it would work in Yosemite and I have the right wifi card). And I get the following:

chmod: Unable to change file mode on /System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/AppleAirPortBrcm43224.kext/Contents/version.plist: Operation not permitted
chmod: Unable to change file mode on /System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/IO80211NetBooter.kext/Contents/_CodeSignature/CodeResources: Operation not permitted
chmod: Unable to change file mode on /System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/IO80211NetBooter.kext/Contents/Info.plist: Operation not permitted
chmod: Unable to change file mode on /System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/IO80211NetBooter.kext/Contents/version.plist: Operation not permitted
chmod: Unable to change file mode on /System/Library/Extensions/IO80211Family.kext/Contents/version.plist: Operation not permitted

Note that that isn't all the errors but all the change file modes give the same "operation not permitted". 

I am thinking Apple has sandboxed OS X even more. Note that I have "allow from anywhere" in my security settings.

**Comment by crypiehef** [comment]
Another note: I verified that system has read/write access to the IO80211Family.kext. So I don't know what's going on.

**Comment by EricPSmith** [comment]
All of these findings are consistent with what's described in this Macworld article on OS X El Capitan's new System Integrity Protection (aka rootless) features, which include no changes to Apple files in /System and other top level directories. 

http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html

Hopefully dokterdok is aware of this and able to develop a workaround. 

Eric

**Comment by derekstavis** [comment]
The pull request #196 helps to fix a issue, relative to this part of OP log:

```
Verifying Bluetooth version... /Users/Thomas/Downloads/Continuity-Activation-Tool-master-2/Continuity Activation Tool.app/Contents/Resources/contitool.sh: line 357: [: 6
6: integer expression expected
NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=6
6, expected 6.
```
