### ISSUE TITLE
Where can i get BCM94331PCIEBT4CAX?

### ISSUE THREAD

**Issue by okonon** [dokterdok/Continuity-Activation-Tool#20]
Where can i get BCM94331PCIEBT4CAX?

**Comment by joshperry** [comment]
Just bought this for $18.58 with free shipping, right part number: http://www.ebay.com/itm/110992306092

**Comment by AndrewAlexMac** [comment]
@joshperry Have you only just bought it, or are you confirming it works too?

**Comment by joshperry** [comment]
@AndrewAlexMac I haven't received it yet. I'll report back when I get it.

**Comment by jeroenvankeulen85** [comment]
joshperry, its the wrong card! you need a BCM94331PCIEBT4CAX you bought a BCM94331PCIEBT4AX
missing the C its the older card with BT2.1

**Comment by joshperry** [comment]
@jeroenvankeulen85 Sheesh, one lousy little letter. I hate eBay's search. Thanks man!
