### ISSUE TITLE
Does CAT work with 10.10.5 public as released on Aug 13?

### ISSUE THREAD

**Issue by TomHTX** [dokterdok/Continuity-Activation-Tool#201]
Can someone please tell me if CAT has been found to work with 10.10.5 public? I have it working on 10.10.3 on a MBP early 2011 15" using the CAX implant and sure do not want to lost it.  Thank you

**Comment by ebernet** [comment]
No, it does not. Tried 10.10.5 update on MBPro, Mac Pro - both worked fine with CAT 2.0.0 and 2.0.1 up until 10.10.4, no longer working after 10.10.5

**Comment by mobile4** [comment]
Does it works with dongles?

**Comment by ebernet** [comment]
I do not know, but it fails at the dongle detection stage that it never completes. I do not have a dongle.

**Comment by TomHTX** [comment]
VERY disappointing.  So now we need to find out if Apple made the same "change" to 10.10.5 that they did in 10.11.  Perhaps if the CAT team can get CAT working for 10.11 that version will also work for 10.10.5?

**Comment by brianvermilyea** [comment]
CAT Worked great for me after updating to 10.10.5.  I'm running on a MBP (early 2011) 15" with transplanted CAX, BT/WiFi.  Screenshot attached with continuity working perfectly.  
![screen shot 2015-08-15 at 8 15 33 pm](https://cloud.githubusercontent.com/assets/11563305/9291841/dbccdd96-438b-11e5-95a4-4c19c5068e4f.png)

**Comment by TomHTX** [comment]
Brian.  Thank you very much.  Sounds like your computer is very similar to mine.  ??? did you just reinstall the same CAT 2.00 again after the upgrade to 10.10.5, or did you have to use the newest version (2.1?) that they are using with El Cap?

**Comment by ebernet** [comment]
Not sure how you got it to work. Tried a clean install on bit the machines I mentioned, various versions of CAT, and none proceed beyond the detection of BT dongles in 10.10.5.

**Comment by brianvermilyea** [comment]
@TomHTX: I downloaded and ran the latest master build: https://github.com/dokterdok/Continuity-Activation-Tool/archive/master.zip.  I did not use the beta build...although, that might have worked, too.  @ebernet: I upgraded the built-in bluetooth card from the BCM94331PCIEBT4 to BCM94331PCIEBT4CAX.  I'm not using an external dongle.  I believe the CAX version has BT 4.0 and the no CAX version does not.  I also believe that that the CAX version was released with the 2012 MBP 15".  Again, I am running on an early 2011 15" model.  If I recall, I was prompted to insert a BT dongle while running CAT.  However, I'm not, so I chose to ignore or skip the dongle detection.  I hope that helps.

**Comment by ebernet** [comment]
Master build - check
updated to the same internal BT - check
My model is the late 2011 MBPro rather than the early 2011
My Mac Pro -2008, with the BT 4.0/Wifi AC card
Again, both machines have been working fine with CAT since 10.0.0, both 1.1 and then 2.0.0. After upgrading to 10.10.5, both fail at the same spot (BT dongle detection). I am not using a dongle nor have one installed. Do not know how it is working for you, but everything I tried fails for me.

**Comment by brianvermilyea** [comment]
Also, for what it's worth, the link to zipped file in my previous post contains files last modified on 8/13/15.  That's newer than the modified date of the beta zip, which is 8/10/15.

**Comment by brianvermilyea** [comment]
@ebernet: Sorry, I'm not sure why it's not working for you.  Were you prompted to skip (or something like that) the dongle detection?  I know I was prompted for something like that while I was running CAT.

**Comment by ebernet** [comment]
Yes, I am prompted to insert dongle and hit any key or hit any key to proceed without dongle. I do and I just get a flashing terminal window title trying various things. Have tried many times, even with latest master.zip with August 13 dates. Is really no one else having this problem?
And again, these are two different computers with different hardware that had no issues until 10.10.5

**Comment by ebernet** [comment]
Is there a way to run CAT in a verbose mode so as I can see what is going on?

**Comment by sd70mac** [comment]
Someone on the Macrumors forums patched it to get it working. <http://forums.macrumors.com/threads/modded-continuity-activation-tool-btle-cards-with-el-capitan-is-working.1890715/page-2>. I'm not sure what changes were made, though.

**Comment by ebernet** [comment]
That's El Capitan. I have seen no mention of the issues with 10.0.5 other than my own. I have tried a clean install of 10.0.5 on both machines, but still to no avail. Is really no one else seeing this?

**Comment by sd70mac** [comment]
Well, I used that version to install on my 11" mid-2011 MacBook Air on 10.10.5, so I know that it works for that configuration at least.

**Comment by mobile4** [comment]
Updated to 10.10.5. Using Gmyle dongle with btoadcom chipset. Macbook Pro 2010. Works perfect.
Steps I did:
1. Unistall CAT. Remove dongle. Reboot.
2. Install 10.10.5 update.
3. Insert dongle
4. install CAT

**Comment by ebernet** [comment]
I can't be the only one with this problem... I reformatted my HD, installed a clean 10.0.5 from recovery partition after formatting, and tried - same issue. Please please, I've been asking for 3+ weeks about this, has anyone else found a solution or seen this?

**Comment by dokterdok** [comment]
Have you tried hitting any other key than the space key when the dongle detection screen is displayed? Cf. issues #106  , #95

**Comment by ebernet** [comment]
You GOT to be freakin' kidding me.... that is EXACTLY what it was. Can't believe that:
a. This has not been fixed
b. That is took 3+ weeks for anyone to mention this as an issue.
At least fix it so that prompt says clearly to hit any key OTHER than the spacebar.... That should only take a minute....

**Comment by TomHTX** [comment]
It worked!!!!  So, after watching cautiously for comments by others, and being very careful to avoid the "spacebar" issue, I went ahead and updated to 10.10.5 this morning, and then immediately ran the latest master dated 8/13/15.  I am pleased to report that it did work, and that continuity and handoff seem to be working on my 2011 MBP 15 with the surgically implanted CAX card.  THANKS to dokterkok and to all who have contributed to this project, and to this thread.  Tom
