### ISSUE TITLE
cloudpaird

### ISSUE THREAD

**Issue by slvrscoobie** [dokterdok/Continuity-Activation-Tool#207]
So after some investigation i've found that under the new 10.11 El Capitan Golden Master there is a process that is failing to start which i believe is the issue why we are unable to get the Continuity / handoff to work. 
CloudPairD which is 'Daemon responsible to registers your device for Handoff and Continuity after signing in to iCloud'
On my 2011 MBP with XXCAX BTLE card installed, I am unable to start it, as it reports that "System does not support continuity"

Both myself and BasicGreatGuy on Macrumors have installed GM, and available handoff check box  after installing CAT, however, neither of us has the cloudpaird deamon running. Neither of us can get handoff to work between devices. 
However, on my 2012 mbp it does work, and cloudpaird is running. 
I think we just need to determine what the requirements are for the cloudpaird to see the system as 'supporting continuity' and maybe we can get El Cap to work with CAT!

**Comment by slvrscoobie** [comment]
So I fixed it!!!
Use a yosemite version (10.10.4 or lower since i think 10.10.5 had issues) of cloudpaird
replace is system/library/coreservices and reboot!!!!

**Comment by jenham** [comment]
Can you post the file I should replace the current one with?

**Comment by slvrscoobie** [comment]
Ill link to my post on the MR forum where i put it. 
http://forums.macrumors.com/threads/modded-continuity-activation-tool-btle-cards-with-el-capitan-is-working.1890715/page-8#post-21810398

**Comment by jenham** [comment]
Thanks!!
