### ISSUE TITLE
10.11 GM 10.11.1b1 on Mid-2010 15" MBP

### ISSUE THREAD

**Issue by displaced** [dokterdok/Continuity-Activation-Tool#213]
Just a few notes on what I've seen with the current beta on the above config.

Firstly, my MBP has been upgraded with the CAX bluetooth/wifi module.

On a CAT Beta version downloaded on 10th August, Continuity would appear to be enabled ("Handoff Supported = Yes" in System Information) but would not actually function in 10.11 GM.

I saw in the commit log that another patch -- to enable a setting in SystemParameters.plist -- has been added to enable Continuity in 10.11.  So, I downloaded the newer version of the beta and retried.

With the latest beta, WiFi was disabled after reboot.  The AirPort icon showed 'no WiFi hardware present'.  I tried to uninstall via CAT, but still no WiFi.  Luckily, the 10.11.1 beta had already downloaded, so I let it install.  That repaired the WiFi kext.

So, in 10.11.1b1, I tried the older CAT beta.  Once again, this appeared to work, but Handoff still didn't work.

I then went through the contitool.sh file in the newest beta to see how the SystemParameters mod worked.  I applied that manually and now all Continuity features work fine!

**Comment by jenham** [comment]
I get the wifi error as well, so by applying that manually it fixed the hardware error?

**Comment by MightyBoo** [comment]
With reference to a similar issue: https://github.com/sysfloat/Continuity-Activation-Tool/issues/1
Can you please detail the process step so we can follow through. Thank you.

**Comment by displaced** [comment]
No -- I had to uninstall the 'new' beta first.  That restored WiFi.

Then, use the old beta and apply the SystemParameters mod.  That got handoff up and running.
