### ISSUE TITLE
Cannot Launch: Tool is Damaged

### ISSUE THREAD

**Issue by mjruss** [dokterdok/Continuity-Activation-Tool#217]
I have downloaded the latest beta.  Upon launching I immediately receive the error:

"Continuity Activation Tools" is damaged and can't be opened.  You should move it to the Trash."

My two options are to cancel and trash the application. 

I did not see this in the issues thread, so am I the only one with this problem?

**Comment by ahovis** [comment]
Same for me.

**Comment by operator911** [comment]
Likewise!

**Comment by slvrscoobie** [comment]
Sheesh people. You need to change your security setting to allow 'from anywhere' first. 
If you're stuck on this, you should probably not be using this mod.

**Comment by mjruss** [comment]
I have long been aware of the security settings governing application launching. However the message normally reads that the application is not from a trusted source and tells you to go to the security settings to make a change if you want to launch it. That is considerably different than an application being labeled as damaged and needing to be dumped in the trash. The difference is not the parent I would think  even to users who are more experienced than average. 

That said, thank you for the assistance.

**Comment by demeeder** [comment]
I have "from anywhere" set up.  When I open the app I get nothing.   Terminal opens and I get ~ root# /Users/XXX/Downloads/Continuity-Activation-Tool-beta-2/Continuity\ Activation\ Tool.app/Contents/Resources/contitool.sh ; exit;

That is all... just a black screen from there.  Do I need to wait more than a minute or so for something to happen?  Had no problems running previous versions prior to OS 10.11

**Comment by TzTerri** [comment]
Same here.
![screen shot 2015-10-02 at 9 07 43 am](https://cloud.githubusercontent.com/assets/14133626/10247160/127c5d84-68e5-11e5-80db-c3fa95c8c882.png)

**Comment by tbezemer** [comment]
The solution to this problem is to 'cd' into the Continuity Activation Tool using the terminal (the terminal sees a .app file as a folder), and running "applet" using the "./applet" command to execute the CAT. From the top of my head the path is something like: "Continuity Acrtivation Tool.app/Contents/MacOS/applet" or something

**Comment by tbezemer** [comment]
And be sure to run the diagnostic option first, and disable SIP as CAT requires it to be disabled to install. You can disable it by rebooting and holding CMD + R to boot into your recovery partition. Then access the terminal from one of the top menus and run the command "csrutil disable". Reboot into OSX 10.11, run  CAT as I explained above to install it. Finally, repeat the steps to re-enable SIP, by running "csrutil enable" in the recovery mode terminal.

**Comment by TzTerri** [comment]
Does this version support bluetooth dongels?

**Comment by tbezemer** [comment]
I don't think it does as of yet. There's info in the beta branch directory on that I think.

**Comment by jjj71** [comment]
same problem for me!

file damaged, move to trash!
please replace it with a working version

I have a mid2011 macbook air

I can't stay without airdrop, thank you

**Comment by mjruss** [comment]
jjj71, see above.  It turns out that that file is not damaged, that is just a bug in the way MacOS is telling us about security.  It SHOULD read that the app is from an unknown developer and therefore cannot be opened per your security settings.  Instead the OS is calling it damaged.

Same solution, though.  Go to System Preferences, Security, General, and allow apps from "Anywhere" to be opened and you will be good to go.

At least as far as LAUNCHING the app.  I got it to launch but then it turned off my WiFi capability and did not activate Continuity, so I had to uninstall/restore.  I guess I will wait for them to get this out of beta or write off Continuity until I can afford a newer MBP.

**Comment by Robiv8** [comment]
@tbezemer
Thanks,
Disable SIP helps.

**Comment by jjj71** [comment]
thanks @tbezemer 
and thanks everybody,
I disabled SIP and now it works

**Comment by roseofwolf** [comment]
Is it possible to activate SIP again after installing? How?
If so, does Continuity continue working properly?
Will this "issue" be addressed in the final version for El Capitan?

**Comment by tbezemer** [comment]
@roseofwolf Please read above. I've given a step by step explanation on this.

@jjj71 you're welcome :)

**Comment by ahovis** [comment]
Well I got it installed and it did the kext modifications on the latest version of El Cap but it kernel panicked over and over when it rebooted :-(  Took overnight to restore from time machine backup. Guess I will wait for fixes before trying again.

**Comment by mjruss** [comment]
Yes.  I got the app launching but it:

A)  Does not activate continuity.
B)  Deactivates my WiFi.

So... Waiting for this to come out of Beta.

**Comment by jenham** [comment]
Do any of you guys have Logitech software installed? I get the same errors whenever I have tried to pair my Logitech products. But as soon as I uninstall Logitech Control Center it works.

**Comment by sbieniek** [comment]
MBP Early 2011. Installed following instructions above (Disable SIP, Run Applet via Terminal, Test, Re-Enable SIP).

Working so far, will open an issue report if I experience any problems.

**Comment by TzTerri** [comment]
Are you using a dongle?

**Comment by mjruss** [comment]
Not sure who you mean, but I am not. I upgraded the hardware inside my MBP 2010 model. It was working fine with CAT until 10.11 was released. Now not even the CAT Beta will enable continuity. And, as I say, it disables WiFi which is a bit problematic. 

Also as I mentioned I do realize this is beta. So I can wait.

**Comment by sysfloat** [comment]
@mjruss 
1. Make sure SIP is turned off via booting into Recovery mode.
2. Make sure allow apps from anywhere is set.
3. Navigate to the location of CAT via the terminal
4. Enter: "sudo 'Continuity Activation Tool.app/Contents/Resources/contitool.sh' -r"
5. reboot and your wifi should work again. 
6. Download the latest beta (2.1.2) and run it. 
If there are still problems send me an email at catbetaelcap@gmail.com and I will try to fix them.

**Comment by mjruss** [comment]
Thank you, I have WiFi back online.  One quick question:  How do I know whether or not I am getting 2.1.2 from the beta page?  The top post says that 2.1.1 is the latest.

**Comment by mjruss** [comment]
Any chance we could re-open this, please?  Five days later, without warning or changing anything else on the computer, my WiFi hardware is missing again.  I have had the computer shut down and back up several times since we resolved the Continuity issue, but today I turned it on and the WiFi is gone again, like it was with the last version of the beta.

I’m using my phone via USB to get online right now, but do not have the data to do that for long.  If nothing occurs to you, please just let me know and I’ll restore the system to the way it was (use the tool to remove the patches).

Thanks!

Mark

**Comment by sysfloat** [comment]
@mjruss That's weird. Verify nvram with (nvram -p) that there's still an entry like "boot-args kext-dev-mode=1" and also check the last modified date of the IO802Family.kext.
