### ISSUE TITLE
2.1.1 with 10.11 El Capitan on Mid-2010 15" MBP

### ISSUE THREAD

**Issue by tmbreuker** [dokterdok/Continuity-Activation-Tool#219]
Hello,

1. Started with an fully functional continuity on my MBP with Yosemite  (with upgraded CAX bluetooth/wifi module) and working CAT.
2. Upgraded MBP to El Capitan. Ofcourse continuity did not work after this.
3. I installed the CAT 2.1.1 beta on my MBP. Result: The AirPort icon showed 'no WiFi hardware present'
4. In uninstalled CAT 2.1.1 beta and wifi is working fine again, but continuity not.

Anyone has a solution? I will the installation (step 3) again, because during the installation I did notice some errors and will post them here.

thx, Tom

**Comment by Rob3r7o** [comment]
http://forums.macrumors.com/threads/modded-continuity-activation-tool-btle-cards-with-el-capitan-is-working.1890715/page-16#post-22006544
http://speedy.sh/EvSE4/Archivio.zip

It's 100% ok

**Comment by tmbreuker** [comment]
Like a charm, thanks a lot Rob3r7o!

**Comment by tmbreuker** [comment]
Strange thing still is: 
I am not able to establish the hotspot via the AirPort icon to my iPhone. I did logout iCloud on all devices and logged in again. Is there by any chance a way to test handoff more specific?

**Comment by godwithus2820** [comment]
Dose it works in MBP 2011-early???
