### ISSUE TITLE
iMac Mid 2011 Stopped Working

### ISSUE THREAD

**Issue by Hackmodford** [dokterdok/Continuity-Activation-Tool#222]
Handoff working in Yosemite without any patches. I just replaced the wifi/bluetooth card inside.

In El Capitan, system report still says Handoff is supported but I cannot get it to work.

I ran the OS X Continuity Activation Tool 2.1.2 and did the diagnostics run and got this:

```
--- OS X Continuity Activation Tool 2.1.2 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: iMac12,1
Verifying Mac board-id...               OK. Long board id detected: Mac-942B5BF58194151B
Verifying OS X version...               Warning: This version of Mac OS X (10.11) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v112 c9036
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is not active. This tool can fix this.
Verifying SIP...                        NOT OK. System Integrity Protection is still enabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

Press any key to go back to the main menu...
```

Did something change in El Capitan? Any suggestions?

**Comment by mobile4** [comment]
Well. The main change in El Cap the CAT is sensitive for is SIP (System Integrity Protection). Which is STILL enabled in your system. IMHO please learn basic for CAT before installing.

**Comment by Hackmodford** [comment]
But should disabling SIP and this tool even be necessary? It was working in Yosemite without making any software changes whatsoever, the only thing I changed was replacing the wifi/bluetooth card.

The chart says that I only need to replace my hardware, no software changes necessary.

**Comment by rotx** [comment]
@Hackmodford 10.11 added SystemParameters.plist - you need to edit that file and set your Board ID to allow Continuity. You can do it booted from Recovery HD or any other boot disk (the file is in /System/Library/Frameworks/IOBluetooth.framework/Versions/A/....)
At least for my Mac, I did not have to disable/re-enable SIP; and I did the edit using vi. YMMV. 
From what I've seen, contitool should be able to make that edit for you (but, obviously, not when you're booted from the system you're trying to edit when SIP is on)

**Comment by Hackmodford** [comment]
@rotx OK, that makes sense. 

Maybe I'm running into this issue https://github.com/dokterdok/Continuity-Activation-Tool/issues/229

When I experimented with running the tool it said that continuity was active and didn't do anything.

**Comment by sysfloat** [comment]
The newest version of CAT (2.1.4) should fix this. 
You need to have SIP disabled before running CAT, you can enable it later after verifying that Continuity works as expected.

**Comment by Hackmodford** [comment]
Confirmed, this fixed the issue.
