### ISSUE TITLE
2.1.2 beta for eicaption on MacBook Pro 2011 late with BCM94331PCIEBT4CAX bluetooth board

### ISSUE THREAD

**Issue by llv22** [dokterdok/Continuity-Activation-Tool#224]
Dear colleagues:

I try to use CAT 2.1.2 to active with my eicaption system on MacBook Pro 2011 late, plugined with BCM94331PCIEBT4CAX bluetooth board.

--- OS X Continuity Activation Tool 2.1.2 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,1
Verifying Mac board-id...               OK. Long board id detected: Mac-94245B3640C91C81
Verifying OS X version...               Warning: This version of Mac OS X (10.11) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. Compatible Broadcom AirPort drivers Brcm4360 Brcm4331 are active
Verifying AWDL status...                OK. Wi-Fi hardware is compatible with AWDL, but no such interface is up. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v151 c5844
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

Press any key to go back to the main menu...

However, after system reboot, system give prompt "wifi driver isn't installed".
Could you help sovle this issue? Perhaps a patch for BCM94331PCIEBT4CAX Bluetooth LTE is needed.

Best Regards
Orlando

**Comment by sysfloat** [comment]
Could you please try to uninstall CAT und use the new verstion (2.1.3)?

**Comment by llv22** [comment]
already fixed it, I have checked it today. will close the issue.
