### ISSUE TITLE
Macbook pro 2011 13" with the wifi-bluetooth card upgraded does not work (worked before)

### ISSUE THREAD

**Issue by NatiqJavid** [dokterdok/Continuity-Activation-Tool#227]
Hey there,

Thanks for your great work, this tool is awesome. I have been using it since Yosemite and it has been working just perfect.
But now after i upgraded to El Capitan, the problem is that i can not activate the CAT anymore. 
My card is the new one, cax, and it worked with Yosemite. I have the LMP version: 0x6.  I dont get why its not working now. 
I have tried running the new CAT 2.0, but i get an "NOT OK" on bluetooth version. its strange. 

Take a look here.

Screendump: 
![screen shot 2015-10-09 at 02 25 06](https://cloud.githubusercontent.com/assets/6737638/10383451/4fa939ee-6e2f-11e5-981c-01cdd7bd04d8.png)

Screendump when i run the tool:
![screen shot 2015-10-09 at 02 25 38](https://cloud.githubusercontent.com/assets/6737638/10383457/61507dec-6e2f-11e5-80e7-1c2b4e879c78.png)

Thank you.

**Comment by sysfloat** [comment]
Please use the current [beta version](https://github.com/dokterdok/Continuity-Activation-Tool/tree/beta).

**Comment by NatiqJavid** [comment]
I forgot to mention that i have tried the beta version. 
Here is the result:

![screen shot 2015-10-09 at 14 40 32](https://cloud.githubusercontent.com/assets/6737638/10393892/db3e0ee4-6e93-11e5-907b-70de74d61e12.png)

**Comment by sysfloat** [comment]
You need to temporarily enable "Allow apps downloaded from Anywhere".
Settings - Security & Privacy.

**Comment by NatiqJavid** [comment]
You sir, are a genius! :D Thank you very much, it solved the problem!!!!
