### ISSUE TITLE
CAT doesn't work with 10.11 on a 2011 Macbook Air

### ISSUE THREAD

**Issue by diegopetrucci** [dokterdok/Continuity-Activation-Tool#228]
It used to work on Yosemite, now it says my hardware can't support it.

I've attached an image that shows the issue.

![schermata 2015-10-09 alle 14 03 45](https://cloud.githubusercontent.com/assets/773004/10393266/a6a85432-6e8e-11e5-9d2c-c33677b384b7.png)

If I scroll back in the terminal:

![schermata 2015-10-09 alle 14 05 25](https://cloud.githubusercontent.com/assets/773004/10393284/e1cb55a0-6e8e-11e5-9c34-b1901fd339ca.png)

**Comment by sysfloat** [comment]
Please use the current [beta version](https://github.com/dokterdok/Continuity-Activation-Tool/tree/beta).

**Comment by diegopetrucci** [comment]
Thanks! Is there a way to mark this issue as "solved"? Or your "invalid" is already enough?
