### ISSUE TITLE
CAT 2.1.3 will not patch white/blacklist if OS X erroneously reports Continuity as active

### ISSUE THREAD

**Issue by operator911** [dokterdok/Continuity-Activation-Tool#229]
Still having a problem with new CAT 2.1.3 (present on previous version of CAT).

Had CAT working on Yosemite previously, continuity was working perfectly.  Usually in past had updated Yosemite, which usually broke continuity, but could always reactivate easily using CAT again, so I was not in the habit of uninstalling CAT before updating the OS.

Now, I updated to El Capitan, (and didn't think to uninstall CAT, which is what others seemed to do to make things work), and now I am getting this issue where Continuity is reported as active by OSX, but continuity does not work.

Running the system diagnostic yields:
--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookAir4,2
Verifying Mac board-id...               OK. Long board id detected: Mac-742912EFDBEE19B3
Verifying OS X version...               Warning: This version of Mac OS X (10.11) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v112 c9037
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.

However, when I try option 1 to Activate Continuity, I get the following:

OS X reports Continuity as active.
No changes were applied.

I have tried reinstalling El Capitan to see if this would wipe out whatever remnants of changes I had from the old CAT that are screwing up the process - no dice.
I have tried to log out of iCloud and log back into iCloud which sometimes fixed things in the past - also no dice.

Any thoughts?  Happy to provide any further diagnostic info to those who support CAT if requested.

Thanks

**Comment by operator911** [comment]
Also tried this:
sudo sh contitool.sh -f

Result is:
Password:
tr: Illegal byte sequence
tr: Illegal byte sequence

--- Initiating Continuity mod ---

-n Disabling OS kext protection...         
OK
Fixing disk permissions...              OKe 
-n Backing up original drivers...          
Would you like to overwrite the existing backup found in /Users/ptai/KextsBackupBeforePatch? 
1) Yes, overwrite
2) No, skip this backup
#? 1
OK. Wi-Fi and Bluetooth kexts were backed up in '/Users/ptai/KextsBackupBeforePatch'
-n Patching blacklist...
NOT OK. Failed to disable the blacklist - no changes were applied. Aborting.

Press any key to go back to the main menu...

**Comment by sysfloat** [comment]
There is no longer a blacklist in the bluetooth kext in El Capitan, that's why it doesn't patch it.
After running CAT, is Handoff available in System Preferences under General?

**Comment by operator911** [comment]
An option for "Allow Handoff" is available, and it is checked off.  
![screen shot 2015-10-10 at 10 28 43 am](https://cloud.githubusercontent.com/assets/14933780/10411634/f36b8234-6f39-11e5-8b9c-d08070f63051.png)

I would note that for some reason this option was available and always checked off after I installed El Capitan, even before attempting to install CAT.
I just tried logging out of iCloud, rebooting, logging back into iCloud, rebooting again, but handoff (i.e. wifi hotspot, and handoff for Safari, message etc) still doesn't seem to work.

**Comment by sysfloat** [comment]
Could you please try to run /System/Library/CoreServices/cloudpaird via the terminal and post what that returns? Also try to use Handoff after running it.

**Comment by operator911** [comment]
Hi Sysfloat,

This is what happens:
Peters-MacBook-Air:CoreServices ptai$ ./cloudpaird
2015-10-10 11:27:26.758 cloudpaird[2458:54784] DEBUG cloudpaird: system does not support Continuity

**Comment by sysfloat** [comment]
Yep that's the problem.
One patch is missing because CAT never actually did anything.
It's quiet weird that Handoff was available before running CAT..
Try to uninstall CAT via terminal with the parameter -r (see README).
After that run CAT again, if that doesn't work run CAT with the paramter -f.

**Comment by operator911** [comment]
Thank you Sysfloat.
So, I tried uninstalling as instructed and got the following text:
![screen shot 2015-10-10 at 11 58 16 am](https://cloud.githubusercontent.com/assets/14933780/10412012/c7e6d85e-6f46-11e5-98b3-a15bca5af41a.png)
Following that I rebooted, and found that the system still reports Continuity as being active.  I then tried running CAT again - first the usual way, which gave me the usual error message of not being able to run due to continuity being active, then with contitool -f, which yielded the following:
![screen shot 2015-10-10 at 12 01 01 pm](https://cloud.githubusercontent.com/assets/14933780/10412022/e8655f60-6f46-11e5-9dfa-840ec5336289.png)

**Comment by sysfloat** [comment]
I'm not able to look into this today but will try my best to do that tomorrow.
Can you please send me an email at catbetaelcap@gmail.com so I can send you a version to test tomorrow?

**Comment by operator911** [comment]
Absolutely.  Thank you.
