### ISSUE TITLE
Compatibility List Chart is incorrect

### ISSUE THREAD

**Issue by freediverx** [dokterdok/Continuity-Activation-Tool#232]
The Compatibility List Chart lists only two rows for iMac, one for models with the Broadcom chip and the other for those with the Atheros chip. 

The row for the Atheros chip mistakenly labels all models as "Mid 2007".  I have a late 2009 27" iMac and it is equipped with the Atheros chip.

This omission led me to mistakenly assume that my iMac had a Broadcom chip since the "Late 2009" model is only displayed on the Broadcom row.

**Comment by sysfloat** [comment]
The compatibility chart states the model when a given CAT compability situation has changed. 
The "Mid 2007" is there because iMacs are equipped with a Atheros since then and the bar then continues in the same color until a new model comes our or the situation changes.
