### ISSUE TITLE
I can't enable Handoff in El Capitan general settings

### ISSUE THREAD

**Issue by franzipol** [dokterdok/Continuity-Activation-Tool#234]
I used the Continuity-Activation-Tool and Airdrop work as expected. The only problem is that the option for enabling Handoff on my Mac doesn't appear at all

**Comment by kylase** [comment]
You need to provide more information such as your Mac model. Otherwise, it will be hard for anyone to give you any comments.

**Comment by franzipol** [comment]
sorry. I'm pasting here the diagnostic of the tool. by the way before i used the version 2.1.3 of the tool and as I wrote before i had airdrop working. A while ago I uninstalled everything and applied the version 2.1.4 and now airdrop is not working anymore. Here is the last diagnostic.

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro6,2
Verifying Mac board-id...               OK. Short board id detected: Mac-F22586C8
Verifying OS X version...               Warning: This version of Mac OS X (10.11) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and uses the legacy Brcm4331 kext. This tool can fix this.
Verifying AWDL status...                OK. No AWDL is active, but the hardware seems to be able to support it. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. Already patched.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.

**Comment by franzipol** [comment]
i forgeot to tell i'm using an ASUS BT400 dongle

**Comment by sysfloat** [comment]
The previous versions of CAT were not compatible with bluetooth dongles, please try the new version (2.2).

**Comment by billyla** [comment]
may I ask where can I download v2.2? I could only found v2.1.3

thanks

**Comment by franzipol** [comment]
i tried and now airdrop is working again and i can enable handoff in the general settings but it's not working

**Comment by franzipol** [comment]
also instant hotspot is not working even if it's reported being supported in the system details

**Comment by franzipol** [comment]
after logging out and in icloud and some reboots everything seems working. The only issue is with airdrop which at first worked flawlessy setting it for "contacts only" but now i have to let it to "everyone" but i don't think it's related to the tool but to something. Everything work as expected. Thank you very much
