### ISSUE TITLE
Dongle Testing

### ISSUE THREAD

**Issue by ylluminate** [dokterdok/Continuity-Activation-Tool#235]
I have a Broadcom dongle here and would be happy to test / debug / troubleshoot if you could use some input.

**Comment by mrwhiggly** [comment]
Me too! Is there a chance to have a new version of CAT which works with dongles in El Capitan?

**Comment by hrubymar10** [comment]
Me too 😌

**Comment by kramsee** [comment]
I can help as well! :+1:

**Comment by sysfloat** [comment]
send me an email, catbetaelcap@gmail.com

**Comment by ylluminate** [comment]
Does this closure indicate that the issue is resolved?  I have never received an email.
