### ISSUE TITLE
Airdrop Not working on 2011 MacBook Pro El Capitan With Wifi Module Upgrade

### ISSUE THREAD

**Issue by claywd1210** [dokterdok/Continuity-Activation-Tool#236]
After upgrading to OS X El Capitan I can no longer use the new airdrop. I have installed the correct module for this to be compatible and it was working before upgrading to El Capitan. 

MacBook Pro 8,2 with internal airport card upgraded. 

People can see and transfer to me, I just can't see or transfer to other people. If anyone needs something in order to track down this bug, please just let me know and I will try to provide it.

**Comment by rabieau79** [comment]
Hi,
I uninstalled CAT before to install El Capitan.
I reboot on recovery mode (cmd R) and I disabled SIP, I reboot, and I installed CAT v2.2
All is ok, wifi, bluetooth, airdrop and handoff.
I reboot on recovery mode to enable SIP. I reboot.
Wifi bluetooth airdrop and handoff work perfectly.
I hope this steps will help you

MBP 8,2 15" late 2011 2,4GHz with BCM94331PCIEBT4CAX wireless card

**Comment by claywd1210** [comment]
I don't know where to get version 2.2. All I can find is 2.1.3. Can you point me in the right direction?

**Comment by rabieau79** [comment]
When you click on the "Download link" on the master page you download the version 2.2 automatically, not the version 2.1.3
the link is https://github.com/dokterdok/Continuity-Activation-Tool/archive/master.zip

**Comment by claywd1210** [comment]
Okay. I completed the following steps but it rendered no juice. 

1.) uninstalled CAT 2.1.4
2.) rebooted
3.) Replaced CAT 2.1.4 with 2.2 in Applications
4.) opened CAT2.2
5.) Installed CAT2.2
6.) Reboot
7.) No Dice
8.) logged in a Guest- it worked. crap.
9.) logged in as myself and signed out of iCloud- it works so long as everyone is set. If I change visibility to contacts only, no dice. 

Still a bug but at least I can airdrop in some capacity again

**Comment by rabieau79** [comment]
Update
Today I have this message "no harware installed" about the wifi card.
I reboot (cmd+R) and disables SIP, all works fine.
I enable SIP, wifi not work.
I uninstalled CAT v2.2.2
Wifi works but no handoff and no continuity :-(
However continuity worked until today

**Comment by leoaf79** [comment]
I had a similar problem caused by file permissions recovery. 
Solved this by disabling sip, uninstalling (recovering) and reinstalling CAT. Then I was able to reenable SIP without any problem.
