### ISSUE TITLE
OSX 10.11.1 Public

### ISSUE THREAD

**Issue by PerfectStory** [dokterdok/Continuity-Activation-Tool#243]
Confirmed working on Late MBP 2011 with bluetooth chip installed, just reinstalled and didn't have to sign out of iCloud for continuity to work.

**Comment by rabieau79** [comment]
Me too, I installed OS X 10.11.1 without uninstall CATv2.2.
Just a message after reboot "CAT no installed"
I reboot to recovery mode, I re-installed CAT and all is ok.

**Comment by pkayhart** [comment]
El Capitan 10.11.1 upgrade. Early 15" 2011 Macbook Pro. Broadcom BCM4360CD 1.0 (7.21.94.29.1a4) replacement Airport Card. Installed the OS update, disable SIP, installed CAT 2.2 w/o previous uninstall. Continuity is working.

**Comment by rabieau79** [comment]
Update
Today I have this message "no harware installed" about the wifi card.
I reboot (cmd+R) and disables SIP, all works fine.
I enable SIP, wifi not work.
I uninstalled CAT v2.2.2
Wifi works but no handoff and no continuity :-(
However continuity worked until today

**Comment by leoaf79** [comment]
I had a similar problem caused by file permissions recovery. 
Solved this by disabling sip, uninstalling CAT (with recovering) and reinstalling CAT. Then I was able to reenable SIP without any problem.

**Comment by rabieau79** [comment]
OK thank you for your solution.
No problem, handoff & continuity work fine

**Comment by claywd1210** [comment]
can you please close this issue as well, it will help keep the boards from cluttering with duplicate issues.
