### ISSUE TITLE
Yosemite Security Update 2015-004 Broke it

### ISSUE THREAD

**Issue by sparky672** [dokterdok/Continuity-Activation-Tool#245]
I installed Security Update 2015-004 to Yosemite 10.10.5 yesterday.  Continuity and Handoff were working fine until this update.

CAT reported that Continuity was "Inactive".  So then I activated it and rebooted.  Still no Handoff both ways.  Then I logged out/in of iCloud on both devices, still no Handoff both ways.

Continuity Phone Calling is still working, it's just Handoff that is totally broken.

Did this last Security Update kill CAT?

-----------------------------

--- OS X Continuity Activation Tool 2.0.0 ---
                 by dokterdok                 

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacPro5,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F221BEC8
Verifying OS X version...               OK. Mac OS X 10.10.5 (14F1021) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.
Verifying BT4 dongles compatibility...  OK. The patch that enables BT4 USB dongles compatibility has already been applied

**Comment by sysfloat** [comment]
Whats the status of Continuity after rebooting in CAT? 

Also is handoff available in System Preferences?

**Comment by sparky672** [comment]
The status is as I posted above... shows everything is fine.

Yes, "Handoff" is available (and ON) in System Prefs.

**Comment by sparky672** [comment]
After installing the new version of CAT, here is the diagnostics...

--- OS X Continuity Activation Tool 2.2 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacPro5,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F221BEC8
Verifying OS X version...               OK. Mac OS X 10.10.5 (14F1021) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying Bluetooth blacklist status... OK. Warning: Blacklist not found in the Bluetooth drivers. An OS X update might have made this hack useless.
                                        However, your Mac model shouldn't need to be removed from that blacklist.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.
--- Modifications check ---

**Comment by sparky672** [comment]
Okay... this is weird....

I simply installed the latest version of CAT and used the diagnostics (option 2).  I did nothing else.  Selecting option 1 simply told me nothing was done because Continuity was already enabled.

However, Handoff, both ways, suddenly started working again.  Wow... I don't know if it's my hardware, CAT, or simply that Handoff/Continuity is just a VERY unreliable feature.
