### ISSUE TITLE
iMac early 2009 how to Patch Board-ID?

### ISSUE THREAD

**Issue by nya2mi2** [dokterdok/Continuity-Activation-Tool#247]
my mac iMac early 2009  with new wireless card BCM94360CD + adapter

el capitan 10.11.1 

Bluetooth cable connection , it does not start . Freeze . Disconnect cable , start , good . In cable re- connection , Bluetooth , handoff available .

how to Patch Board-ID?

**Comment by claywd1210** [comment]
Still having issues?

**Comment by nya2mi2** [comment]
Yes.
mac does not start when you connect a Bluetooth module. 
Connect the Bluetooth module after turning on the mac, it is good.

**Comment by claywd1210** [comment]
are you getting a kernel panic?

**Comment by nya2mi2** [comment]
No, leave the white screen, it is freeze.

**Comment by claywd1210** [comment]
Alright, try this. Shutdown the mac. Once it is powered down, turn it on and immediately hold the v key. Screen should turn black. Have a camera ready and take a picture or video of the error displayed on the screen.

**Comment by nya2mi2** [comment]
no.
It does not do if you want to connect a Bluetooth module. Do not even in Verbose mode. Remain white screen, it is freeze.It is helpless. El Capitan, because you have changed the USB configuration, and can not be recognized, I think.

**Comment by nya2mi2** [comment]
![img_8163](https://cloud.githubusercontent.com/assets/13653549/11803956/0c6d6ac6-a343-11e5-83be-96ab4aa354b6.JPG)

**Comment by nya2mi2** [comment]
At start-up and cut the Bluetooth module. After starting to connect the Bluetooth module, in usb recognition, you can use all the features. Bothersome.

**Comment by nya2mi2** [comment]
![img_8165](https://cloud.githubusercontent.com/assets/13653549/11804324/432b91e8-a346-11e5-9cf9-16759ea02aee.JPG)

**Comment by claywd1210** [comment]
Check your boot arguments by running 

"sudo nvram -p"
check the boot-args line. If it is empty then very that SIP is not enabled (disable it in recovery if it is).

"csrutil status"
everything should come back disabled.

Use this to fix your boot-args.

sudo nvram boot-args="kext-dev-mode=1 rootless=0"

If that doesn't work then uninstall CAT with recovery and then reboot. Grab the latest version and verify your boots-args and SIP. Once verified, reinstall CAT(latest) and try it again.
