### ISSUE TITLE
Option 6 (quitting) results in a different terminal window closing

### ISSUE THREAD

**Issue by legoadk** [dokterdok/Continuity-Activation-Tool#248]
When more than one Terminal window is open, and CAT is quit from within (by entering option 6 on the main screen), a different terminal window is actually closed. This may result in lost work if other terminals have active programs running within them.

OS X 10.10.5

**Comment by legoadk** [comment]
The patch for this bug, if it works like I think it does, actually issues Command Q to the entire terminal application. This will quit every open terminal, as well – actually more destructive than the original issue that closed a different random window. A suggestion would be to instead issue Command-W, which only closes the currently focused tab within the current window. The issue with this is that it still leaves the Terminal application open — good if you have other terminals open, bad if CAT was the only open program. Tough bug to work around!

**Comment by sysfloat** [comment]
@legoadk Command-W will close the window but CAT will stay in the dock as "Not Responding". 
CAT opens a new instance of Terminal running as root and you shouldn't use it to run anything else. The new solution would then quit that instance. Any instance of the normal Terminal not used by CAT remain unaffected.

**Comment by legoadk** [comment]
Ah, that totally makes sense. In that case, ignore my previous comment :)
