### ISSUE TITLE
Early 2011 MBP on 10.11.1 not working w/ CAX. Was working fine on 10.10.x

### ISSUE THREAD

**Issue by bdwilson** [dokterdok/Continuity-Activation-Tool#249]
Early 2011 MBP w/ 6s here - I'm at my wits end trying to get this working in El Capitan (swapped the card and everything was working great in Yosemite). In El Capitan, I've disabled SIP, run CAT 2.2.1 (and tried previous versions, betas too, but restored from recovery prior to my latest try). 

Profiler shows that BTLE, Handoff and Instant Hotspot ARE supported. These functions are not working, even after logging out of iCloud on both devices. No Instant Hotspot, handoff, or Airdrop functions work. I also cannot get MacID working which is frustrating (was working great on Yosemite). 

I've even tried to change out cloud /System/Library/CoreServices/cloudpaird from a 10.10 install since someone said that would help w/ the handoff functions. I would at least think that MacID would work? Bluetooth does work because I can pair with my 6s and use hotspot over bluetooth, so I don't feel like it's a hardware problem.

Any tips? Do I need to be using a different version of CAT? What about cloudpaird?

![CAT2.2.1](https://dl.dropbox.com/u/853747/Jing/2015-10-26_2136.png)
![Profiler](https://dl.dropbox.com/u/853747/Jing/2015-10-26_2141.png)
![OS](https://dl.dropbox.com/u/853747/Jing/2015-10-26_2143.png)

**Comment by iGGNoRe** [comment]
Works fine for me on the same model. I couldn't get it to initially work for me until I signed out of iCloud on my laptop and signed back in to "register" the device as continuity eligible I guess. If that doesn't fix it, let me know.

![screen shot 2015-10-27 at 10 03 41 am](https://cloud.githubusercontent.com/assets/2638727/10765884/33948b2a-7c92-11e5-8d57-8c68b6579d4c.png)
![screen shot 2015-10-27 at 10 04 37 am](https://cloud.githubusercontent.com/assets/2638727/10765890/37ce0aea-7c92-11e5-939a-8a230a081a29.png)
![screen shot 2015-10-27 at 10 04 24 am](https://cloud.githubusercontent.com/assets/2638727/10765894/3a2c7524-7c92-11e5-8e66-4fd5cd58af6a.png)

**Comment by bdwilson** [comment]
@iGGNoRe curious if you have a 6s or not? I've seen posts about 6s potentially being the issue here.  Unfortunately, I didn't get this working before I got a 6s, so I can't confirm if my 6 worked.

**Comment by sysfloat** [comment]
Have you tried running /System/Library/CoreServices/cloudpaird in terminal?
What output do you get?
Also try [these](https://support.apple.com/en-us/HT204678) steps and wait some time, it might just take a few mins.

**Comment by bdwilson** [comment]
@sysfloat here is what I get: [Errors](https://dl.dropboxusercontent.com/u/853747/Jing/2015-11-02_2023.png)

**Comment by fastasleep** [comment]
I had trouble getting this and MacID working again myself, with a 2011 MBP, but have finally figured it out. Here's a list of things I did that eventually got it working — not sure what exactly was the trick but it was definitely some combo of the below. :)

- check your Startup Items in Users & Groups, for some reason I had MacID listed three times. Deleted the extras, not sure if this mattered but hey.
- updated both MacID Mac/iOS to v1.3 (when replacing the Mac version, be sure to tell it to check for updates — it previously did not automatically do that)

- Reset SMC (and PRAM while I was at it):
https://support.apple.com/en-gb/HT201295

- Turn SIP off again
restart command-R, terminal: csrutil disable

- Turned off Bluetooth and:
- Delete all BT prefs:
http://kanecheshire.com/blog/2015/01/26/defeating-bluetooth-on-os-x/
- Clear BT cache:
http://kanecheshire.com/blog/2014/12/15/clear-bluetooth-cache-for-core-bluetooth-on-mac-os-x/

- Sign out of iCloud, sign back in

- Restart

VOILA.
iPhone suddenly turned up in MacID when I opened the app
Continuity started working shortly after, am seeing Safari/Mail windows in focus show up on iOS or Mac, depending.

**Comment by bdwilson** [comment]
Thanks @fastasleep! I believe the key here was getting rid of the BT prefs and Cache.  I updated to MacID 1.3.1 today and noticed there was an option that shows up on the "Add iOS Device" menu if a device isn't found that says "Reset Bluetooth Settings & Reboot".  I selected this and MacID and Continuity options appear to be working now. Thanks for the tip; your info should be in the FAQ.
