### ISSUE TITLE
my early 2011 MBP is not woking with el capitan

### ISSUE THREAD

**Issue by adhamr** [dokterdok/Continuity-Activation-Tool#251]
--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 

If you want to activate Continuity using a USB Bluetooth 4.0 dongle,
then unplug it and plug it in now. The script will continue once it is detected.

Press any key to continue without a USB Bluetooth 4.0 dongle...

--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 

--- Initiating system compatibility check ---

Verifying SIP...                        OK
Verifying Mac model reference...        OK
Verifying Mac board-id...               OK
Verifying OS X version...               Warning: This version of Mac OS X (10.11) is Experimental! Only partially tested on El Capitan
Are you sure you want to continue?
1) Yes
2) No
# ? 1

Verifying Wi-Fi hardware...             OK
Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity Current LMP Version=4, expected 6. Aborting.

Press any key to go back to the main menu..

**Comment by sysfloat** [comment]
Your MacBook would require an upgraded AirPort card or a bluetooth dongle.
If you've got one of the above the newest version (2.2.2) should fix this.
