### ISSUE TITLE
If I keep SIP off should I use 3d party utility to repair permissions?

### ISSUE THREAD

**Issue by mobile4** [dokterdok/Continuity-Activation-Tool#252]
Subj.

**Comment by claywd1210** [comment]
Just don't... use this and be happy. "sudo /usr/libexec/repair_packages --repair --standard-pkgs --volume /"

**Comment by claywd1210** [comment]
If your all fixed up can you please close this issue.

**Comment by mobile4** [comment]
claywd1210 What is I'm asking for is should I use a 3d party utility to repair permissions? Cause El Cap has no disk permission utility any more. And if SIP is off system will not repair permissions by itself. From El Cap side permissions cannot be damaged cause of SIP. But if SIP is off it can happen. Am I right?

**Comment by claywd1210** [comment]
I think you may just be misinformed. You can still verify and repair your own permissions. Use the following

sudo /usr/libexec/repair_packages --verify --standard-pkgs / 
That will verify your disk. Next, you can repair by typing in:

sudo /usr/libexec/repair_packages --repair --standard-pkgs --volume /

**Comment by mobile4** [comment]
claywd1210 Thank you for your attention. That commands are for /USR only right?
If SIP is off files in /BIN and /SBIN can be modified and as a result permissions can be damaged. Can I use the same commands for /BIN and /SBIN?
Actually the commands you wrote are the commands which the Disk Utill run before. Should I make script to run it faster? It's a bit boring to retype it. Any 3d party Disk util for El Cap?

**Comment by claywd1210** [comment]
"/usr/libexec/repair_packages"    <- this is the location of the repair operation

"--verify --standard-pkgs /"          <- this is the parameters passed to the program 

"--volume /"                                 <- this is the location that the operation operates on. 

So that being said, the commands will look at all the items included in --standard-pkgs and repair after verifying them .

**Comment by mobile4** [comment]
Ok! Now it is clear for me. Thank you! +1:
