### ISSUE TITLE
CAT 2.2.2 on 2010 MBP with BCM94331PCIEBT4CAX card

### ISSUE THREAD

**Issue by kahuna1342** [dokterdok/Continuity-Activation-Tool#255]
I can get CAT working just fine if I leave SIP off. However, if I enable SIP, I get the No WiFi hardware installed problem. I have had this same setup all through Yosemite with no problems. I am currently running 10.11.1 Any thoughts or other information I should provide?

**Comment by jballigood** [comment]
AS far as Understand it, SIP has to remain off in El Captain.

**Comment by claywd1210** [comment]
Yup, leave it off. The WiFi kext is modified... if SIP is on then it can't load the modified WiFi kext. Thus, no WiFi.

**Comment by kahuna1342** [comment]
Had it working under 10.11.0 with SIP enabled. Have not been able to make it work that way since. Oh well, guess I will just leave SIP off.
