### ISSUE TITLE
2.2.1 doesn't recgonize kext-dev-mode status on El Capitan 10.11.1 

### ISSUE THREAD

**Issue by delingren** [dokterdok/Continuity-Activation-Tool#256]
I seemed to have successfully patched my system. But handoff is not working, although OS X reports that my bluetooth is capable of handoff. CAT also doesn't think kext-dev-mode is enabled in auto check. I have already set it to 1 in Clover. I'm not sure if I did everything correctly. See my post on tonymacx86: http://www.tonymacx86.com/network/147734-continuity-handoff-capable-apple-mini-cards-pcie-mini-pcie-adapters-34.html#post1140086

Any help is appreciated. thanks.

**Comment by claywd1210** [comment]
Put it in your boot-args with "rootless=0" and leave it there. Also, if you are running an SSD, you can run the command "trimforce enable" and it will write the kext dev mode to the system so it doesn't have to sit in your boot arguments.
