### ISSUE TITLE
MBP half 2015 El Capt problem after restoring backup from MBP with CAT

### ISSUE THREAD

**Issue by DrAma999** [dokterdok/Continuity-Activation-Tool#262]
I've bought a brand new MBP continuity and handoff should work out of the box but it isn't.
I started thinking that the issue could be caused by a full restore from a time machine backup of an old where I used to work with CAT and a Bluetooth dongle.
I made all the sanity check about WIFI, bluetooth etc, my iPad and my iPhone see each other without a problem but my MBP it doesn't seem to see them and vice-versa.
I've tried to uninstall disabling SIP, but It shows me this error.
>Verifying SIP...                        OK
Restoring kexts...                      OK. No backups made with the tool were found, using the OS X Recovery Disk backups.
Mounting Recovery HD...                 OK
Reinstalling original Apple drivers...  OK
Applying correct permissions...         OK
Updating kext caches...                 OK
Updating system caches...               OK
Disabling any HCI switch behavior...    OK
Verifying system kexts signatures...    OK. 1 or more unsigned drivers were found. OS kext security protection won't be changed to prevent issues.
Patching ContinuitySupport...           Set: Entry, ":Mac-[hidden]:ContinuitySupport", Does Not Exist
OK.
36:71: execution error: System Events found an error: Impossibile obtain  (-1728)
OK. Automatic continuity check disabled.
>> I've translated last 2 lines from italian

**Comment by claywd1210** [comment]
lol, if you just bought a brand new MBP then you need to uninstall continuity activator and take it to the apple store. They will fix/replace whatever may not be working or troubleshoot it for you for free.

**Comment by DrAma999** [comment]
Just reistalled the OS and imported the account

**Comment by claywd1210** [comment]
And it worked?

**Comment by DrAma999** [comment]
Sure, probably making a full restore from TM restores also kext and stuff, by re-installing and just restoring the account using migration assistant everything worked.

**Comment by claywd1210** [comment]
okay great. can you close your issue then for us?
