### ISSUE TITLE
Can't work in 10.11.2

### ISSUE THREAD

**Issue by Drshu** [dokterdok/Continuity-Activation-Tool#266]
I disabled SIP,but tool tell me,I need to disable SIP.

**Comment by Quel11** [comment]
Rebooted using CMD+R. Opened terminal. Used "csrutil disable". CAT did not give the SIP error. MBpro early 2011 with the 2012 wifi card on 10.11.2.

**Comment by bocsitanc** [comment]
@Drshu, make sure you're running the latest CAT version. Had the same issue, downloaded and installed latest version, worked like a charm.

Cheers!

**Comment by Drshu** [comment]
@Quel11 @bocsitanc 
I used CAT2.1.3,and disabled SIP,and Initiating system compatibility check is no problem.
Verifying SIP...                        Ok. System Integrity Protection is already disabled

but it's can't install,
Verifying SIP...                        OK
To continue you need to disable System Integrity Protection and come back here.

**Comment by bocsitanc** [comment]
@Drshu, i believe the latest version is v2.2.3- 2015-12-07. This version worked great for me.

Cheers!

**Comment by Zeblouze** [comment]
Same as Quel11 here. I had to : 

Uninstall CAT 2.2.2. and reboot
reboot in recovery mode to disable csrutil : cmd + R / terminal / csrutil disable
install CAT 2.2.2.
reboot.
everything works well immediately , no need to sign out from iCloud or else.

hope it helps.

**Comment by Drshu** [comment]
@bocsitanc @Zeblouze  successful!thx~

**Comment by claywd1210** [comment]
Wonderful!, close the issue?
