### ISSUE TITLE
"Wi-fi: No hardware installed"

### ISSUE THREAD

**Issue by jacobgelman** [dokterdok/Continuity-Activation-Tool#270]
After installing CAT on my Mid 2011 Mac Mini running 10.11.2, my Wi-fi menu says "Wi-fi: No hardware installed."

![menu](https://cloud.githubusercontent.com/assets/3182119/12039277/dc79d828-ae13-11e5-8284-f66db527d3ae.png)

**Comment by UnicumZ** [comment]
Hello,
I have the same problem, I've disabled SIP, uninstall CAT using Uninstall with Recovery and then and re-install CAT 2.2.3 and I still having trouble with the wifi.
And I have a weird message;
Verifying system kexts signatures...OK. 1 or more unsigned drivers were found. OS kext security protection won't be changed to prevent issues. 

![capture d ecran 2015-12-30 a 21 33 46](https://cloud.githubusercontent.com/assets/16495372/12060445/0a44c27e-af3e-11e5-8dd3-e9bf058ef2fc.png)

Menu sometimes says «No hardware installed » or suddenly the Wifi quit randomly ...
I have to reboot several times to have the wifi working. 
Nothing listed in the #253 worked for me.
MacBook pro 15" early 2011 on 10.11.2

**Comment by claywd1210** [comment]
Disable SIP and leave it off. Also, add kext-dev-mode=1 to your boot arguments. 

That will allow the unsigned driver to continue.

**Comment by claywd1210** [comment]
* that will allow the unsigned (because the tool modifies a copy of the original kext) to load and your WiFi will return.

**Comment by UnicumZ** [comment]
Hello Clayton,
Thanks for your help :-)
Well I use this command (In the terminal):
sudo nvram boot-args=kext-dev-mode=1
And reboot,  I have also left the SIP disabled but it still didn't work. 
Same message about the kext. 
And no more wifi card detected. 
After many reboot I've decided to re-install 10.11.2 (clean install, from an USB key and erasing the drive). 
I am here right know. 





Envoyé de mon iPhone 6 S Plus !!!
Na !

**Comment by skrimaging** [comment]
had this issue many times since El Capitan and always resorted to reinstalling my OSX without erasing my drive.. thought it was my Mac but now I see others have the same issue. Yosemite never gave me these issues.. 

For now, I am waiting for a fix before attempting to reinstall this tweak.. wouldn't want to reinstall OS every few weeks.

**Comment by walkky** [comment]
Why is this closed with "won't fix" resolution? Other issues mention the problem again and again, and still no sustainable fix seem to exist up to today.
