### ISSUE TITLE
Continuity inactive - MBP early 2011 with BT4 dongle

### ISSUE THREAD

**Issue by AndreiPopoviciu** [dokterdok/Continuity-Activation-Tool#273]
I installed the app, my iphone 5s (latest update) IS connected via bluetooth on my MBP early 2011 (el capitan 10.11.2) and everything works good: hotspot, messages/face time and unlock app but in the general settings doesn't appear the option to check handoff.

I tried to reinstall the continuity and on the compatibility check everything is good, besides the first line: 
"OS X reports Continuity as inactive"
--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,1
Verifying Mac board-id...               OK. Long board id detected: Mac-94245B3640C91C81
Verifying OS X version...               Warning: This version of Mac OS X (10.11.2) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         WARNING. Unknown Bluetooth features have been detected (code:6). This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v187 c8891
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.

**Comment by sysfloat** [comment]
Which dongle do you have? Could you post the content of System Information - Bluetooth?

**Comment by AndreiPopoviciu** [comment]
So, here are the informations from system report bluetooth:
 Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Name:	Andrei’s MacBook Pro
  Address:	00-1A-7D-DA-71-0C
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	No
  Instant Hot Spot Supported:	No
  Manufacturer:	Cambridge Silicon Radio
  Transport:	USB
  Firmware Version:	8891
  Bluetooth Power:	On
  Discoverable:	Off
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0A12
  Product ID:	0x0001
  HCI Version:	0x6
  HCI Revision:	0x22BB
  LMP Version:	0x6
  LMP Subversion:	0x22BB
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On

My dongle is: Trust.
It’s code is: 18187-03

**Comment by sysfloat** [comment]
Your dongle is not supported. Only broadcom dongles are supported.. You should try to get a dongle with a broadcom 20702 chip if you want to get Continutiy working.
