### ISSUE TITLE
Kernel Panic on reboot (early 2011 15' MBP, OS X 11.11.3, BCM94331PCIEBT4CAX AirPort card)

### ISSUE THREAD

**Issue by lha8mfm** [dokterdok/Continuity-Activation-Tool#279]
Today I've replaced my AirPort board with the recommended one. I ran system diagnostics in CAT a everything was ok; I ran the activation process and everything went fine!

After that, I rebooted my MacBook and got a kernel panic (see picture attached). Only when I disconnected the board I was able to boot up the computer and then uninstall the continuity activation patch, which replaced my kexts back to normal and allowed my computer to back up. Any advice?

I'm running CAT 2.2.2 and OS X 11.11.3 on an early 2011 15' MacBook Pro with a BCM94331PCIEBT4CAX AirPort card.

![system diag output](https://cloud.githubusercontent.com/assets/16901012/12584794/174f4d82-c441-11e5-8b63-f5f4fd56fe5a.png)
![photo-2016-01-26-15-18-19_fullsizerender](https://cloud.githubusercontent.com/assets/16901012/12584810/30147f22-c441-11e5-9a2f-b33473218576.JPG)

**Comment by mobile4** [comment]
I have Macbook Pro early 2011, 15'. With replaced card (BCM94331PCIEBT4CAX). MAC OS 10.11.3. Everything works. Airdrop sometimes fails but not very often. Try to reinstall system.

**Comment by lha8mfm** [comment]
Ok, I will give it a try this weekend and get back to you! Thanks!

**Comment by lha8mfm** [comment]
I did a clean OS X install and ran through the activation process of CAT. Kernel panic persisted. 

Could this be due to a faulty AirPort board? The computer boots fine until I ran CAT.

**Comment by mobile4** [comment]
lha8mfm. Well. It looks like something wrong with CAX4 card. I got my card from the real disassembled macbook. So it is 100% native. Please pay attention - the CAX card you need for CAT has 4 connectors. Your old card has just 3 connector. As I remember there is some trick for cable connection - at least 1 connector has to stay unused. Sorry! I cannot remember which one exactly! Please try to find it yourself. If you fail to find I will try to remove back cover from my notebook to make photos for you.

**Comment by mobile4** [comment]
lha8mfm
- The shortest antenna cable connects to J2
- The middle antenna cable connects to J1
- The longest antenna cable connects to J3
- The additional connection point (J0) can be left empty.

**Comment by lha8mfm** [comment]
Both my original board and the CAX one have 4 connectors. I think it's the 2010 generation that has that 3 connector board.

**Comment by mobile4** [comment]
Ok. We have a similar computers. You did a fresh install and checked CAX connection. And I hope you installed CAT exactly as it mentioned - SIP off and Gatekeeper off. IMHO new CAX is broken.

**Comment by lha8mfm** [comment]
Yes, I did everything as you just described. Any advice on where I can get a decent CAX board?

Thanks for all the help until now ;)

**Comment by mobile4** [comment]
lha8mfm 
Just for example:
http://www.amazon.com/BCM94331PCIEBT4CAX-MacBook-A1278-A1286-AirPort/dp/B00NV1IXV8/ref=sr_1_1?ie=UTF8&qid=1455091269&sr=8-1&keywords=BCM94331PCIEBT4CAX

**Comment by lha8mfm** [comment]
Just an update: I bought this board http://www.amazon.co.uk/dp/9928101175 and here's what happened. The Wi-Fi is connected when I start up, but Bluetooth isn't detected. Because of that I can't even run CAT, obviously... I'm trying some troubleshooting steps but have you got any idea to help me?

**Comment by lha8mfm** [comment]
Rebooted the computer multiple times and tried running an clean OS X install I had on an external HDD and upon returning to my regular installation everything worked. I'm a little confused... But hey, everything seems to be fine! :)
