### ISSUE TITLE
10.11.4 15E56a  reports no compatible hardware

### ISSUE THREAD

**Issue by robinkaty** [dokterdok/Continuity-Activation-Tool#286]
--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,3
Verifying Mac board-id...               OK. Long board id detected: Mac-942459F5819B171B
Verifying OS X version...               Warning: This version of Mac OS X (10.11.4) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and uses the legacy Brcm4331 kext. This tool can fix this.
Verifying AWDL status...                OK. No AWDL is active, but the hardware seems to be able to support it. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=4, expected 6.
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v42 c847
Verifying Login Item...                 OK. Login item for Auto Continuity Check is set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

**Comment by colonelclick** [comment]
I have the same problem on Mac Pro 5,1

As soon as I install 10.11.4 it says no bluetooth compatible hardware. When I use Time Machine to revert back to 10.11.3 it is working fine again.

**Comment by robinkaty** [comment]
I am running 10.11.4 official and it seems to work on the 2011 mac book pro 17" But that beta 10.11.4 beta5/6 messed it up.

**Comment by colonelclick** [comment]
I used Recovery Console to reinstall OS X onto my existing drive. It put on 10.11.4, kept all my apps and settings, and restored the bluetooth functionality. Handoff is still working.
