### ISSUE TITLE
Macbook Pro 8,2 OSX 10.11.3 - Activated but not working

### ISSUE THREAD

**Issue by mhedhliGVIT** [dokterdok/Continuity-Activation-Tool#287]
Installed a compatible card, ran v2.2.3 of CAT on OS X 10.11.3. All reports says Handoff should be working. All settings are correct on iPhone, iPad and Macbook Pro. No bueno with handoff. Let me know if you need anything more than whats below.

CAT DIAGNOSTIC BELOW

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,2
Verifying Mac board-id...               OK. Long board id detected: Mac-94245A3940C91C80
Verifying OS X version...               Warning: This version of Mac OS X (10.11.3) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v151 c5844
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. Already patched.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. The whitelist is correctly patched with your board-id
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Wi-Fi driver Brcm4331 was already removed
Verifying legacy Wi-Fi card patch...    OK. The patch is already done. Old Broadcom Wi-Fi cards may work.
--- Modifications check ---

RELATIVE SYSTEM PROFILER INFO BELOW:

BLUETOOTH

 Apple Bluetooth Software Version:	4.4.3f4 16616
  Hardware, Features, and Settings:
  Name:	Colonel Panic
  Address:	7C-C3-A1-44-BE-B9
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	Yes
  Instant Hot Spot Supported:	Yes
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	20702A3
  Firmware Version:	v151 c5844
  Bluetooth Power:	On
  Discoverable:	Off
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x05AC
  Product ID:	0x821D
  HCI Version:	0x6
  HCI Revision:	0x16D4
  LMP Version:	0x6
  LMP Subversion:	0x2297
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On

WIFI

 Software Versions:
  CoreWLAN:	11.0 (1101.20)
  CoreWLANKit:	11.0 (1101.20)
  Menu Extra:	11.0 (1110.33)
  System Information:	11.0 (1100.1)
  IO80211 Family:	11.1 (1110.26)
  Diagnostics:	5.1 (510.88)
  AirPort Utility:	6.3.6 (636.5)
  Interfaces:
en1:
  Card Type:	AirPort Extreme  (0x14E4, 0xF5)
  Firmware Version:	Broadcom BCM43xx 1.0 (7.21.94.136.1a1)
  MAC Address:	7c:c3:a1:44:be:b8
  Locale:	FCC
  Country Code:	US
  Supported PHY Modes:	802.11 a/b/g/n
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 149, 153, 157, 161, 165
  Wake On Wireless:	Supported
  AirDrop:	Supported
  Status:	Connected

**Comment by mhedhliGVIT** [comment]
Just an update... magically from the train while tethered Handoff began working. Perhaps it's environmental issues with my home network. Will test from the office network and provide additional feedback.

**Comment by ErikUri** [comment]
Hey, I had the same issue as you. Handoff started working when I opened up the Airdrop menu. I noticed you also don't have wireless a/c supported. Let me know if you get that working!

**Comment by sysfloat** [comment]
@mhedhliGVIT It sometimes takes some time to sync the data that you now got a Continuity compatible device to the server.

@ErikUri The AirPort card from the 2012 MacBook Pro does not support 802.11ac. It is therefore not possible to enable it.
