### ISSUE TITLE
CAT compatible with OS X 10.11.4

### ISSUE THREAD

**Issue by Cougar159** [dokterdok/Continuity-Activation-Tool#290]
I have the MBA 11' mid 2011 with 10.11.3 and CAT installed. Everything is working normally, including Hands Off and Continuity.

Just updated the OS X to 10.11.4.

Everything still works fine.

**Comment by mobile4** [comment]
MB Pro 15' early 2011 running public 10.11.4 (with replaced CAX). iOS 9,3 iPhone 6 Plus. Everything work - Handoff, Airdrop, Modem. What I did on MB. Installed update. Rebooted with CMD+R. Checked SIP. It was still disabled. Rebooted normally. Started CAT and installed it. As I said above everything work.

**Comment by xmangel** [comment]
MBA 13' mid 2011 with  OSX 10.11.4 and CAT installed, well-activated. Everything is working normally except Airdrop.  I've already added my infos as a new contact in my own contact book as some others suggest. However the Airdrop doesn't work. Any ideas ?

**Comment by Cougar159** [comment]
Same here!

Everything works well except Airdrop.

And thats the most important feature for me…

**Comment by mobile4** [comment]
Did you try to make new pairing in bluetooth setting?

**Comment by AbeEstrada** [comment]
MBP 15" 2010 with replaced AirPort (BCM94331PCIEBT4CAX) everything works on public 10.11.4
