### ISSUE TITLE
HELP please macbook pro retina late 2013

### ISSUE THREAD

**Issue by claudiorox** [dokterdok/Continuity-Activation-Tool#295]
Hi, I have problem with my macbook pro retina 2013. I had a macbook air 2011 with this tool installed, i upgraded to this new macbook and i used a backup from the macbook air with this tool installed. Now i tryed to uninstall it from the macbook pro but i still can't use airdrop heeelp. I think i meesed things up
<img width="1102" alt="image" src="https://cloud.githubusercontent.com/assets/18374167/14408121/483478ea-ff2a-11e5-8529-d4cedc1de078.png">

**Comment by s54gasm** [comment]
I think the only way around the issue is to wipe and reinstall OS X as new.

**Comment by claudiorox** [comment]
Could someone please tell me how can I reinstall osx el capitan keeping all my files and actual settings but just resetting the system files ? Is it possible ?

**Comment by kramsee** [comment]
I'm doubting that your issue has anything to do with CAT. The changes made on your MBA 2011 wouldn't be ported through a restore of a TimeMachine backup to a new machine. The output of the CAT uninstallation even says that CAT isn't installed (undoubtedly not in clear manner).

You could run the following command, to identify the one unsigned driver. But I guess that won't be the culprit as well.

    echo "$(find /System/Library/Extensions/*.kext -prune -type d | while read kext; do codesign -v "$kext" 2>&1 | grep -E 'invalid signature|not signed at all'; done )"

Airdrop is quite buggy, maybe you have some luck debugging it following the instructions in this [answer](http://apple.stackexchange.com/a/212086/55761)
