### ISSUE TITLE
Macbook 8,2 & BCM94331PCIEBT4CAX - Only 802.11 a/b/g/n support (no ac)

### ISSUE THREAD

**Issue by ErikUri** [dokterdok/Continuity-Activation-Tool#297]
Hey,

I've installed the bluetooth&wifi in my early 2011 macbook pro and got handoff and airdrop working with this tool. However, wireless ac isn't listed as a mode on my en1 interface. Is there any way to enable this?

Thanks

**Comment by sysfloat** [comment]
The MacBook Pro 2012 does not support 802.11ac. [See the Technical Specifications](https://support.apple.com/kb/SP694?locale=en_US)
