### ISSUE TITLE
Should I even use the CA-Tool for activation?

### ISSUE THREAD

**Issue by emojidatabase** [dokterdok/Continuity-Activation-Tool#302]
10.10.5: No Airdrop but everything else
10.11.4: Airdrop but no Handoff and no instant hotspot

Thanks

I only used diagnostics. CAT-Output:

--- OS X Continuity Activation Tool 2.2.3 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as active
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacPro4,1
Verifying Mac board-id...               OK. Short board id detected: Mac-F221BEC8
Verifying OS X version...               Warning: This version of Mac OS X (10.11.4) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v118 c9123
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is not active. This tool can fix this.
Verifying SIP...                        NOT OK. System Integrity Protection is still enabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

Press any key to go back to the main menu...

**Comment by sysfloat** [comment]
Could you please provide more details? OS version, model, dongle/card..
Thanks!

**Comment by emojidatabase** [comment]
Solved.

Sorry. 
Turned out that I could manage it 
- first by replacing System/Library/CoreServices/cloudpaird with an oler version. 
- Since OS X 10.11.6 everything works out of the box.

My Hardware
http://www.osxwifi.com/apple-broadcom-bcm94360cd-802-11-a-b-g-n-ac-bluetooth-4-0-with-adapter-for-macpro-2009-and-macpro-2010
