### ISSUE TITLE
Late-2011 MBP with GMYLE dongle, LMP Version=0

### ISSUE THREAD

**Issue by foulked16** [dokterdok/Continuity-Activation-Tool#303]
I am running OS X El Capitan (10.11.4) on a Late-2011 MBP. I have a GMYLE Bluetooth 4.0 USB dongle and I am trying to set up Continuity Activation Tool. I opened the application, ran the script, inserted the dongle, and it aborted, saying my LMP Version=0, expected 6. I've pasted the System Diagnostic output below. Any idea why I'd be getting LMP Version=0?

--- OS X Continuity Activation Tool 2.2.3 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,2
Verifying Mac board-id...               OK. Long board id detected: Mac-94245A3940C91C80
Verifying OS X version...               Warning: This version of Mac OS X (10.11.4) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. Compatible Broadcom AirPort drivers Brcm4360 Brcm4331 are active
Verifying AWDL status...                OK. Wi-Fi hardware is compatible with AWDL, but no such interface is up. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. 3rd party Bluetooth hardware detected
**Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=0, expected 6.**
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v0 c15216
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is not active. This tool can fix this.
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

**Comment by ylluminate** [comment]
Mine seems to pass with the https://github.com/RehabMan/OS-X-BrcmPatchRAM (following the NATIVE MAC (ie, not hackintosh) instructions of putting `BrcmPatchRAM2.kext` into /S/L/E/ (that is to say /System/Library/Extensions/)), but then after doing this my system has a panic that requires a goodly amount of work to get back into working condition after repairing the Extensions and permissions, etc.

**Comment by dwinsemius** [comment]
The instruction at https://github.com/RehabMan/OS-X-BrcmPatchRAM/blob/master/README-Mac.md say to install in /Library/Extensions/ for OSX 10.11 and above. They also say you need to first edit boot-args.
