### ISSUE TITLE
El Cap 10.11.5 Public and CAT compatibility proof

### ISSUE THREAD

**Issue by mobile4** [dokterdok/Continuity-Activation-Tool#304]
Please anyone who already tested El Cap 10.11.5 and CAT confirm compatibility (or incompatibility).
It will be nice if you submit configuration of you MAC and iOS version also.

**Comment by mobile4** [comment]
If you afraid of latest 10.11.5. I just installed it on MBP 15 early 2011 with CAX card. CAT works. Continuity hand off and airdrop - everything works.

**Comment by mwoolweaver** [comment]
It works for me but there are a couple issues 

13-inch late 2011 MacBook Pro OS X El Capitan 10.11.5 and iPhone 6 (jailbroken)iOS 9.1

proof that it works 

http://imgur.com/zyYQl0f


and the only issue i have is this

http://imgur.com/2oFBzZ5

**Comment by frizby66** [comment]
Works on MBP Early 2011 15” with upgraded internal card. Uninstalled CAT, upgraded, reinstalled CAT…fully working

**Comment by mobile4** [comment]
mwoolweaverю I'm not sure. I guess you should fix permissions.

**Comment by TzTerri** [comment]
Had to use the installer twice after upgrading but working great on my 17 inch early 2011 Macbook Pro with a dongle.

**Comment by mwoolweaver** [comment]
@mobile4 this was on a fresh install so everything is default. . . 

here are what the permissions are currently 

![screen shot 2016-05-20 at 9 27 49 pm](https://cloud.githubusercontent.com/assets/5729320/15445912/ed5487c2-1ed1-11e6-9786-b21eb1a61bd5.png)

I haven't messed with  any permissions so i don't know why they'd be different from what the should be, if they are different. . .

**Comment by mactofou** [comment]
Hello everyone , I am French and my English are bad !!!! I have a macbook pro 13 2009 with asus usb bt400 and osx 10.11.5 . But cat does not work !!! I tried twice and twice a Kernel panic !!!!
Help

**Comment by AbeEstrada** [comment]
MBP mid 2010 15" with new AirPort card BCM94331PCIEBT4CAX

I updated my computer from the Apple Store and everything worked fine, I didn't have to run the CAT app and I have WiFi and BT working.

**Comment by mwoolweaver** [comment]
@AbeEstrada does Continuity work?

**Comment by AbeEstrada** [comment]
@mwoolweaver Continuity works on 10.11.5 after using the CAT app

![10.11.5](https://cloud.githubusercontent.com/assets/7937/15477388/8b7ec51a-20d1-11e6-863c-029d954577e6.png)
