### ISSUE TITLE
Unable to copy extended attributes for backup of original IOBluetoothFamily.kext & IO80211Family.kext (operation not permitted)

### ISSUE THREAD

**Issue by mwoolweaver** [dokterdok/Continuity-Activation-Tool#305]
Setup in question:

13-inch Late 2011 MacBook Pro w/ upgraded internal hardware (BCM94331PCIEBT4CAX) running OS X El Capitan 10.11.5

![screen shot 2016-05-21 at 12 22 33 am](https://cloud.githubusercontent.com/assets/5729320/15988159/363c4ef8-300b-11e6-9918-c91c77d5ded2.png)
 
_____________
Issue:

So I had to do a fresh install (not because of CAT) of OS X El Capitan 10.11.5 and when I ran the Continuity Activation Tool it gave these errors. 

![screen shot 2016-05-18 at 11 57 48 am](https://cloud.githubusercontent.com/assets/5729320/15446501/a0181bf6-1ee8-11e6-9cc2-250fed467873.png)

not sure how or if this will effect me down the road if the need to restore the original kext ever arises but everything (continuity, instant hotspot, AirDrop) works as it should.

Also worth noting:

The permissions on the files in question are as follows

![screen shot 2016-05-21 at 12 13 06 am](https://cloud.githubusercontent.com/assets/5729320/15446510/e39296b8-1ee8-11e6-8a10-92907a34f51d.png)

**Comment by sysfloat** [comment]
These extended attributes are not needed for the kexts so I told cp to ignore them in the newest version.

**Comment by mwoolweaver** [comment]
alright. Just thought i'd report my findings. . .
