### ISSUE TITLE
Backing up original drivers failed due to read only file system

### ISSUE THREAD

**Issue by mwoolweaver** [dokterdok/Continuity-Activation-Tool#308]
- OS Version: fresh install of macOS Sierra 10.12 Developer Beta 1
- Mac model: Late 2011 13-Inch MacBook Pro
- Dongle or replaced card?: replaced card
- Used dongle/card: BCM94331PCIEBT4CAX

Your Issue:
fails to make Backup of original Kexts due to read only file system

http://pastebin.com/FByptnmn (used pastbin.com due to formatting issues)

**Comment by develrow** [comment]
Have the same identical problem 

OS:          clean build of Sierra 10.12 Beta 1
Model:      MacBook Air mid-2011
BT card:   No replacement card needed
Issue:       Fails to make Backup of original Kexts due to read only file system

**Comment by sysfloat** [comment]
Do you have the new iCloud "Desktop & Documents" feature on?

**Comment by develrow** [comment]
No I don't - However same problem with iCloud Desktop & Documents ON or OFF

**Comment by sysfloat** [comment]
Do you have the same error as @mwoolweaver with "AppTranslocation" ? 
I think this might be a new feature by apple to keep the directory structure of the users home directory private. Not sure why it would be read only though, I just tested it 3 times with different users and it always worked.

Where are you running CAT from? The Applications folder or somwhere else? Did it ask you for any special permissions that you denied?

**Comment by mwoolweaver** [comment]
I ran CAT from the downloads folder where it went when I downloaded it like I have always done.

Also worth noting is Airdrop is the only thing working for me...

**Comment by sysfloat** [comment]
Ok, I hope Apple released some info on this soon.

I am already working on a fix and will soon push it. You might need to uninstall CAT and reinstall it when the new version is out.

**Comment by develrow** [comment]
Originally ran from downloads folder, running from Applications folder solves read only issue, but still no handoff ... Install log attached


[Continuity Install log.pdf](https://github.com/dokterdok/Continuity-Activation-Tool/files/316993/Continuity.Install.log.pdf)

**Comment by sysfloat** [comment]
Works fine for me even when running from the Downloads folder. 

So the workaround for now seems to be to run the app from /Applications

**Comment by develrow** [comment]
Well no....
The install runs, and the readonly issue doesn't occur but Handoff is still NOT working. Options do not appear under settings, general on macOS.

**Comment by sysfloat** [comment]
@develrow I meant regarding this issues topic, the read-only error.

Did you use 2.3? I had hoped that I fixed it with this version.

**Comment by develrow** [comment]
Didn't notice you'd released a new build...downloaded and installed - Handoff now working!
Thanks!!

**Comment by mwoolweaver** [comment]
So running from /Applications did fix the read only file system error is gone! And all the continuity features claim to be working 

![screen shot 2016-06-15 at 4 35 54 pm](https://cloud.githubusercontent.com/assets/5729320/16098492/de5793ee-3318-11e6-9914-c89fcb9501d3.png)
![screen shot 2016-06-15 at 4 43 59 pm](https://cloud.githubusercontent.com/assets/5729320/16098494/e0050852-3318-11e6-9d80-62d208c6fea4.png)

But I don't actually have continuity working for what ever reason...

I have signed out of iCloud on both my MBP and my iPhone 6 

Also worth noting is when i try to setup Back to my Mac I get 
![screen shot 2016-06-15 at 4 55 38 pm](https://cloud.githubusercontent.com/assets/5729320/16098702/08794036-331a-11e6-992d-3326ac6ff755.png)

So maybe it Apple's Server not updating or something. . . .

**Comment by develrow** [comment]
Continuity working here, able to handoff apps between iOS and macOS...
AirDrop also working.
Universal clipboard also working.

**Comment by mwoolweaver** [comment]
So I came back today to report that handoff and Instant Hotspot started working randomly for some  reason. . . 

Also worth noting is haven't messed with CAT at all since the my last comment on this issue. . .
