### ISSUE TITLE
--- DO NOT INSTALL ON OS X EL CAPITAN 10.11 ---

### ISSUE THREAD

**Issue by adiroren1** [dokterdok/Continuity-Activation-Tool#315]
Hello Everyone,

- OS Version: **10.11.5**
- Mac model: **MacBook Pro Early 2011**
- Dongle or replaced card?: **Replaced Card**
- Used dongle/card: **BCM94331PCIEBT4CAX**

I tried to install your program on my MacBook Pro but after every restart I wasn't able to use Wi-Fi at all...
I tried to uninstall it, and accidentally chose "Uninstall with recovery" (or something like that). After a the uninstall process the program ask to restart the Mac. From that period I could't run my Mac and had to restore it to its factory settings. It's a terrible feeling... (BTW, I've no backup to my files, which is stupid, I know, but I learned a huge lesson from this accident). I'd be glad if you could do something to make this program work on OS X El Capitan before you work on a program for an operation system that's not yet released (macOS Sierra)... It would be nice, though, if you could remove the "recovery" options or create a new section which called "Advance Settings" for developers or professional users. It's unnecessary...

I would appreciate it if you could give this matter your serious and immediate attention.

All the best!

**Comment by sumsethan** [comment]
use “csrutil enable --without kext”in recovery can fix this issue，I had same problem，and I sloved it by this

**Comment by sysfloat** [comment]
@adiroren1 doing what @sumsethan said does fix this issue. I updated the documentation accordingly.
