### ISSUE TITLE
Successfully tested OS X 10.11.6 and iOS 9.3.3

### ISSUE THREAD

**Issue by mobile4** [dokterdok/Continuity-Activation-Tool#318]
Just for those who afraid of update to the latest OS X 10.11.6 and iOS 9.3.3.
Tested on MBR 2011, early 2011, 15' (replaced card) and iPhone 6 Plus. Everything works!

**Comment by aquilafedele** [comment]
Does Airdrop between the Mac and the iPhone work as well?
I am in your exact condition (except that I have a iPhone 6S) and I am not able to make Airdrop work. All the handoff and continuity features work perfectly 👍

**Comment by mobile4** [comment]
aquilafedele Airdrop works. Everything works.
