### ISSUE TITLE
contitool.sh login incorrect

### ISSUE THREAD

**Issue by Jeffrey91** [dokterdok/Continuity-Activation-Tool#326]
- OS Version: macOS Sierra 10.12 Beta4
- Mac model: MacBook Pro 15" early 2011
- Dongle or replaced card?: replaced card
- Used dongle/card: from newer MacBook

Your Issue: 
Had CAT installed on Yosemite and it worked great. On El Capitain it didn't worked and now I have tryed to install it again on Sierra. After launching CAT it asks for the admin password, but in the contitool.sh it says login incorrect.

Steps done to try to fix the issue:
Disabled SIP

**Comment by sysfloat** [comment]
CAT is using Apple Script to run as root. Double check that you've entered the correct password.
