### ISSUE TITLE
2012 rMBP is NOT supported by Apple for auto unlock 

### ISSUE THREAD

**Issue by Kazom** [dokterdok/Continuity-Activation-Tool#333]
Unlock with Apple Watch is limited to 2013 and newer. Can we get a working patch for 2012 retina MacBooks?

**Comment by cybercatgurrl** [comment]
As far as I'm aware this requires 802.11ac hardware for time of flight calculations to work. You can upgrade your airport card and it will work.

**Comment by sysfloat** [comment]
@cybercatgurrl is right, you will need 802.11ac hardware.

This can also be read in the wiki under [compatibility](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility).
