### ISSUE TITLE
WatchOS3 Unlock Possible?

### ISSUE THREAD

**Issue by dmavromatis** [dokterdok/Continuity-Activation-Tool#341]
Have you tried [these steps](https://github.com/dokterdok/Continuity-Activation-Tool/wiki#cant-open-the-tool)?

Is there already an open topic for this issue?

Please include the following information.

- OS Version: 10
- Mac model: MacBook Pro (15-inch, Early 2011)
- Yes, installed new card -- and handoff is working.

Your Issue: WatchOS 3 unlock -- doesn't show the option in the menu to unlock using watch?  Is this a feature we can enable?

**Comment by ahm322** [comment]
Same thing here.. would love to see this working

**Comment by felipe-bustamante** [comment]
Same issue... thank you!!

**Comment by Stephkax** [comment]
Same Issue.
MBP Pro Early 2013
Doesn't show the option in the menu.
Following this url : http://www.apple.com/macos/how-to-upgrade/
It is not compatible : 

Auto Unlock
Supported by Mac models introduced in mid 2013 or later.
Requires an Apple Watch with watchOS 3 and an iPhone 5 or later.

Thank you.

**Comment by Ge0rges** [comment]
Indeed MBPs up to mid-2012 seem to be able to support these features but don't.

**Comment by Stephkax** [comment]
May be a wifi card problem. 802.11 ac.
I will try next week with an other wifi adapter bcm94360csax.
But where unlock fonction Check to display the option ? That's the question.

**Comment by Ge0rges** [comment]
It isn't there on those models. Would probably have to find the hidden plist that enables it I assume.

**Comment by dmavromatis** [comment]
@Ge0rges That's what I'm thinking as well -- because they are probably checking based on computer model not wifi capabilities thus it probably won't display that setting in the prefs unless we flip the bit via the CAT or manually by editing a plist.

**Comment by Stephkax** [comment]
For information:
https://networkingnerd.net/2016/09/21/apple-watch-unlock-802-11ac-and-time/

**Comment by Hackmodford** [comment]
It is working for me on my Mid 2011 iMac with replaced wifi/bluetooth internal card. I did not need to reactivate after upgrading from 10.11 to 10.12

**Comment by JimmyPastel** [comment]
@Hackmodford I have the same Mac, and all was working fine in 10.11 and when I updated to beta versions in 10.12., but I made a clean install when final version was launch and I can't make it work again. It's good to know that you have it all working,

ps don't make an clean installation XD

**Comment by Stephkax** [comment]
Hi all,
It is working for me too with my rMBP Early 2013 with bcm94360csax.
Never see the checkbox with the older card.

**Comment by Hackmodford** [comment]
Watch unlock didn't work this morning. Went back to settings and the box was unchecked.

**Comment by Hackmodford** [comment]
Rerunning the tool seems to have fixed handoff and watch unlock. (I believe it just re-patched my board id to the compatibility list)

**Comment by Hackmodford** [comment]
Handoff is working fine. But unlocking with watch seems to fail. It gives the message that it's trying to unlock, but then just shows me the password box.

**Comment by sysfloat** [comment]
You will need a 802.11ac card to get it working. I changed the compatibility in the [wiki](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility) to reflect that.
