### ISSUE TITLE
Does CAT support macbookpro 2011 late auto-unlock by watchOS 3

### ISSUE THREAD

**Issue by llv22** [dokterdok/Continuity-Activation-Tool#350]
Please include the following information.

- OS Version: 10.12 (sierra release)
- Mac model: MacBook Pro (13-inch, Late 2011)
- Dongle or replaced card?: replaced card - BCM94331PCIEBT4CAX Airport card WIFI+BT Bluetooth 4.0
- Used dongle/card: 

Your Issue:

NO "Allow your apple watch to unlock your Mac" option in system preference->Security&Privacy

**Comment by frizby66** [comment]
This is an issue with the BCM card not supporting 802.11 ac. This is needed for Apple Watch Unlock. Only work around so far is to replace the card for one of these http://www.quickertek.com/products/Ucard.html <http://www.quickertek.com/products/Ucard.html>

This issue has been covered already.

**Comment by sysfloat** [comment]
As @frizby66 already said, you'll need a 802.11ac card to get it working.
