### ISSUE TITLE
CAT on Mid 2011 MacBook Air MacOS 10.12 no longer working after update

### ISSUE THREAD

**Issue by z00n1e** [dokterdok/Continuity-Activation-Tool#352]
- OS Version: 10.12 - iOS 10.1
- Mac model: Mid 2011 MacBook Air (4,1)
- Dongle or replaced card?: Unnecessary
- Used dongle/card: N/A

Your Issue: After installing Sierra and reinstalling CAT, the option for Handoff is shown, but it doesn't function. It did function correctly on 10.11 with an iPhone 6S. Now with 10.12 and an iPhone 7, it no longer functions (same computer). Is this possibly because I didn't uninstall CAT before I upgraded? Both devices are on the same WIFI, same iCloud account, with bluetooth on.

Steps done to try to fix the issue:
Uninstall and reinstall CAT. Reboot both devices. Toggle bluetooth and Handoff, on both devices.

Thank you very much

**Comment by philostein** [comment]
Same issue here, exact same MBA model.

Handoff appears in General Preferences. Handoff icons are shown in the app switcher/Dock. Bluetooth connects when clicking the icons (HardwareGrowler notifications), and immediately disconnects again. For example, Safari opens a new tab, but fails to load the Handoff web page. Numbers activates, but fails to open the spreadsheet. Copy and paste Handoff doesn't work.

No Handoff compatible apps/pages on my Mac appear on my iOS devices. Handoff works fine between two iOS devices running iOS 10 and iOS 10 9.

Hope a fix is found! This app has kept my Mac relevant for the last couple of years. :)

**Comment by CCelik84** [comment]
Did you try to sign out and then sign in again to iCloud? It is prompted to do so in the terminal window after CAT is installed. 

I also have the exact same MBA model and Handoff works fine with 10.12 and 6s with iOS 10. 
Another cause might be iphone 7. You may try with 6s. 

My only issue is that Auto Unlock with Apple Watch is not available under the Security & Privacy settings. I cannot use the Auto Unlock function with my Watch OS3. Any ideas?

**Comment by philostein** [comment]
@CCelik84 I didn't sign out and in of iCloud, because it usually rebuilds my entire file system and photo library (about 44GB worth), which can take days to shake out. I've had CAT work without signing out/in. How was it for you? Painful or smooth?

**Comment by philostein** [comment]
I took the plunge and signed out of/into my iCloud account, and Handoff/Universal Clipboard work again!

The process of re-downloading iCloud files hasn't been too painful (so far), thanks to macOS Sierra and iCloud Photo Library keeping a lot of files in the cloud anyway. I'll only go through this when I'm away from work for at least a couple of days though…

**Comment by z00n1e** [comment]
Just tried that too, all working now! Don't know why I didn't try that earlier.

Thanks!

**Comment by CCelik84** [comment]
@philostein I have around 20 GB in iCloud drive but as you mentioned most of it is on the cloud. That's why it didn't take long to build up the drive again. However, it was painful to see all files disappear when I first logged out. :)
