### ISSUE TITLE
Unlock with Apple Watch Option not available in Security & Privacy Settings

### ISSUE THREAD

**Issue by CCelik84** [dokterdok/Continuity-Activation-Tool#354]
Please include the following information.

- OS Version: 10.12 Sierra
- Mac model: MBA Mid 2011 (4,2)
- Dongle or replaced card?: No 

Your Issue:

Handoff, Continuity, Airdrop all work well. However, In the General Tab of Security & Privacy settings, I Auto-Unlock with Apple Watch checkbox is not available. Therefore, I cannot turn on Unlock with Apple Watch feature. 

Any suggestions? Any users with MBA Mid2011 having the same issue? 

Steps done to try to fix the issue:

**Comment by CCelik84** [comment]
To solve the problem, I logged out and logged in again to iCloud in all devices. Restarted all of them. Wifi and BT are on. Two factor authentication is selected in iCloud and confirmed. All the necessary steps Apple explained are done. In System Summary report, under Wifi, I see that Unlock over wireless option is enabled. However, still Unlock via WatchOS3 does not work and the Toggle On/Off is not available under Security & Privacy.

**Comment by sysfloat** [comment]
You need a 802.11 Wi-Fi card to get Auto Unlock working. I just updated the Wiki to include that. Please check the wiki [here](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility) for the reason.
