### ISSUE TITLE
Apple Watch unlocking not working

### ISSUE THREAD

**Issue by sytler** [dokterdok/Continuity-Activation-Tool#356]
Have you tried [these steps](https://github.com/dokterdok/Continuity-Activation-Tool/wiki#cant-open-the-tool)?

Is there already an open topic for this issue?

Please include the following information.

OS Version: Sierra 10.12
Mac model: 2011 17" Macbook Pro
Replaced card - BCM94331PCIEBT4CAX

Is apple watch unlocking supported? because I cant find this option in Security&Privacy->general
thanks

**Comment by atutrone** [comment]
Same issue here.  Re-enabled SIP without kext and no unlock option to be seen.  Also tried logging out and logging back in to iCloud on all devices.  

Everything else works on Sierra though, at least for me.  

Macbook Pro 15" Early 2011.

Broadcom ID:  BCM94331PCIEBT4CAX

Bluetooth Low Energy Supported: Yes
Handoff Supported:  Yes
Instant Hot Spot Supported: Yes

**Comment by sysfloat** [comment]
Please refer to the readme and [wiki](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility) next time. You will need a 802.11ac capable card.
