### ISSUE TITLE
How do I uninstall the tool?

### ISSUE THREAD

**Issue by StetsonRamey** [dokterdok/Continuity-Activation-Tool#364]
Have you tried [these steps](https://github.com/dokterdok/Continuity-Activation-Tool/wiki#cant-open-the-tool)?

Is there already an open topic for this issue?

Please include the following information.

- OS Version:
- Mac model:
- Dongle or replaced card?:
- Used dongle/card:

Your Issue:

Steps done to try to fix the issue:

**Comment by 1git** [comment]
run the tool again and pick option 3 or 4 depending on if you created backups when you initially ran the tool...
