### ISSUE TITLE
Sierra Handoff works using only hardware upgrade or not?

### ISSUE THREAD

**Issue by sparky672** [dokterdok/Continuity-Activation-Tool#381]
- OS Version:  Sierra 10.12.3
- Mac model: Mac Pro 5,1
- Dongle or replaced card?:  Replaced card
- Used dongle/card:  [Upgraded card](http://www.osxwifi.com/apple-broadcom-bcm94360cd-802-11-a-b-g-n-ac-bluetooth-4-0-with-adapter-for-macpro-2009-and-macpro-2010) as per compatibility chart (BCM94360CD + adapter)

Your Issue:

I used to use CAT in Yosemite and it was working.  Then I upgraded the Wifi/BT card and Sierra 10.12.3 and cannot get Handoff working at all.  (Yes, I disabled/removed CAT because this hardware solution is supposed to work without it.)

[I upgraded the card in my Mac Pro (5,1)](http://www.osxwifi.com/apple-broadcom-bcm94360cd-802-11-a-b-g-n-ac-bluetooth-4-0-with-adapter-for-macpro-2009-and-macpro-2010) as per the [compatibility chart](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility#airport-extreme-card-upgrades).  Airdrop and Instant hotspot are working, but I cannot get Handoff or Universal Clipboard to do anything in either direction.  Nothing happens at all.

My system report:

```
  Apple Bluetooth Software Version:	5.0.3f1
  Hardware, Features, and Settings:
  Name:	Mac Pro
  Address:	ac-bc-32-eb-c7-ee
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	Yes
  Instant Hot Spot Supported:	Yes
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	20702B0
  Firmware Version:	v131 c9230
  Bluetooth Power:	On
  Discoverable:	On
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x05AC
  Product ID:	0x828D
  HCI Version:	4.0 (0x6)
  HCI Revision:	0x240E
  LMP Version:	4.0 (0x6)
  LMP Subversion:	0x4183
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Desktop
  Composite Class Of Device:	0x380104
  Device Class (Major):	0x01
  Device Class (Minor):	0x01
  Service Class:	0x1C0
  Auto Seek Keyboard:	On
```

Steps done to try to fix the issue:

I did all the regular stuff; rebooted, toggled Handoff settings on both devices, logged in and out of iCloud on both devices, toggled Bluetooth on/off on both devices, etc., etc, etc...

I ordered a new hard drive so I can do a clean install of Sierra.  I am hoping somebody can confirm that Handoff is still working in Sierra for a hardware configuration where the Wifi/BT card is upgraded.

**Comment by MridangS** [comment]
same with me AirDrop is working but nothing else
Macbook pro late 2011 (MacOS Sierra)

**Comment by sparky672** [comment]
> same with me AirDrop is working but nothing else
> Macbook pro late 2011 (MacOS Sierra)

Today, finally, I can conclusively confirm that **all Continuity features are working** in Sierra 10.12.3 in a 2012 Mac Pro model 5,1 with the upgraded Wifi card (BCM94360CD + adapter); and **WITHOUT using CAT**.

After three days of troubleshooting, rebooting, flushing caches, zapping PRAM, installing a clean OS, installing/uninstalling CAT, logging in/out of iCloud, etc. etc... this simple process seems to have finally unclogged the pipes:

1. Shut down
2. Start up and zap the PRAM
3. Log out of iCloud
4. REBOOT or shut down and start back up (this is the step I always missed)
5. Log into iCloud

Everything should start working immediately.  

NOTE:  Not sure if zapping the PRAM or some other minor thing done just previous to that procedure has anything to do with it.
