### ISSUE TITLE
Kext backup - "read-only file system"

### ISSUE THREAD

**Issue by fastasleep** [dokterdok/Continuity-Activation-Tool#387]
- OS Version:  10.12.3
- Mac model: MBP 8,2
- Dongle or replaced card?: Replaced card

Your Issue:
Last couple times I reinstalled CAT, I got these issues during installation

Backing up original drivers...          
mkdir: /var/folders/fp/75t_04px4x7gtd0t819hty0h0000gn/T/AppTranslocation/7D0E33B4-8A02-4AAA-9C1F-9CC035CD8C3C/d/KextsBackupBeforePatch: Read-only file system
cp: /var/folders/fp/75t_04px4x7gtd0t819hty0h0000gn/T/AppTranslocation/7D0E33B4-8A02-4AAA-9C1F-9CC035CD8C3C/d/KextsBackupBeforePatch/IOBluetoothFamily.kext: Read-only file system
[etc.]
cp: /var/folders/fp/75t_04px4x7gtd0t819hty0h0000gn/T/AppTranslocation/7D0E33B4-8A02-4AAA-9C1F-9CC035CD8C3C/d/KextsBackupAfterPatch/IO80211Family.kext/Contents/version.plist: Read-only file system
NOT OK. IOBluetoothFamily.kext backup failed. IO80211Family.kext backup failed.

Steps done to try to fix the issue:
Nothing, not sure it's an issue as I was able to uninstall and reinstall just now to fix a missing WIFI hardware issue due to a crash yesterday, and everything is working again AFAIK.

**Comment by fastasleep** [comment]
Had another instance of the missing WIFI hardware issue, under similar circumstances. The first time I had random apps freezing up until I hard rebooted, after which I had the missing WIFI hardware icon (Bluetooth was present though). I uninstalled and reinstalled CAT, and things were working fine for a while. Just yesterday though I was working and got a sudden complete freeze of everything and had to hard shutdown and restart, and got the missing WIFI hardware icon again. Booting into Recovery and doing csurtil disable brought it back though, without any other steps. If I csurtil enable though, it goes back to missing WIFI. Haven't tried reinstalling CAT yet to see if I can enable it again, but wondering if this all has something to do with the read-only errors I was getting above.

**Comment by cedstrom** [comment]
Run ```xattr -d com.apple.quarantine Continuity\ Activation\ Tool.app``` in the Terminal and it will remove the quarantine extended attribute.  This will stop AppTranslocation which is what is causing this.  See https://lapcatsoftware.com/articles/app-translocation.html

**Comment by sysfloat** [comment]
The newest beta will check for the quarantine extended attribute, refuse to continue if it's present and will show the necessary steps needed to fix the issue.

**Comment by MDz1985** [comment]
Still needed to remove the quarantine extended attribute (2.6 beta 6)

**Comment by robog0bo** [comment]
I'm getting hangs on reboot after installation on Sierra with 2.6b6, possibly related to sandboxing/quarantine as I launched CAT directly from the Downloads folder after unzipping. I was getting backup failure until I ran `xattr -d com.apple.quarantine Continuity\ Activation\ Tool.app` 

Is it possible there's something more than the quarantine extended attribute causing the sandboxing?
