### ISSUE TITLE
Macbook Pro Early 2011: Question

### ISSUE THREAD

**Issue by MikeeI** [dokterdok/Continuity-Activation-Tool#394]
Is it possible to activate CAT without a dongle? CompatibilityChart says i need hardware upgrade BUT i only need **Universal Clipboard** 

- OS Version: 10.12.5 (16F73)
- Mac model: Macbook Pro Early 2011
- Dongle or replaced card?: NO
- Used dongle/card: NO

Thank you for your answer

**Comment by sysfloat** [comment]
I'm currently not aware of any way this is possible.
