### ISSUE TITLE
Is CAT Project abandoned?

### ISSUE THREAD

**Issue by fabiojuniorrr** [dokterdok/Continuity-Activation-Tool#398]
Is this project abandoned? I'd really like to get CAT to work on my MacBook Pro 5,5 running macOS Sierra installed through dosdude1 macOS Sierra Patcher, but it seems that everyone is having the same boot freeze issue, with no workarounds found over the web so far.

**Comment by sysfloat** [comment]
No it's not working on fixing the issues now.
