### ISSUE TITLE
Not working after upgrade to High Sierra

### ISSUE THREAD

**Issue by demeeder** [dokterdok/Continuity-Activation-Tool#403]
**UPDATED:  WORKS with SIP disabled.**

- OS Version: 10.13
- Mac model: MBP 13" Late 2011
- Dongle or replaced card?: Replace Card
- Used dongle/card: BCM94331PCIEBT4CAX

Your Issue: Tool has worked flawlessly for several OS X updates.  I also have not been required to disable SIP.  However, after updating to 10.13 (High Sierra), the tool does not appear to enable handoff or continuity (per System Report). Also, can't seem to get airdrop to work either, but that is least of my concerns.  Below is the report from the Continuity Tool.

--- OS X Continuity Activation Tool 2.4b5 ---
                 by sysfloat                  
           original by dokterdok              
                                              

--- Initiating system compatibility check ---

Verifying Mac model reference...        OK
Verifying Mac board-id...               OK
Verifying OS X version...               Warning: This tool wasn't tested on OS X versions higher than 10.10. Detected OS version: 10.13
Are you sure you want to continue?
1) Yes
2) No
#? 1
Verifying Wi-Fi hardware...             OK
Verifying Bluetooth version...          OK
Verifying Bluetooth features...         OK
Verifying kexts readability...          OK
Verifying Wi-Fi whitelist status...     OK
Verifying legacy Wi-Fi card patch...    OK
Verifying old Wi-Fi kext presence...    OK
Verifying Login Item...                 OK. Auto Continuity Check off

--- Initiating Continuity mod ---

Disabling OS kext protection...         nvram: Error setting variable - 'boot-args': (iokit/common) general error
OK
Fixing disk permissions...              OK
Backing up original drivers...          mkdir: /var/folders/8t/

----
_Then there are a bazillion lines that start with - "cp: /var/folders/8t/"... and end with "read-only file system"_
----
NOT OK. IOBluetoothFamily.kext backup failed. IO80211Family.kext backup failed.
Skipping blacklist patch...             OK
Skipping BT4 USB dongle patch...        OK
Patching whitelist......................     OK
Cleaning up old Wi-Fi kext...           WARNING. Failed to delete the legacy Brcm4331 Wi-Fi kext. Continuing.
Applying legacy Wi-Fi card patch...     OK
Updating kext caches...                 OK
Updating system caches...               OK
Backing up patched drivers...           mkdir: /var/folders/8t/

----
_Then there is another bazillion lines that start with - "cp: /var/folders/8t/"... and end with "read-only file system"_
----

NOT OK. IOBluetoothFamily.kext backup failed. IO80211Family.kext backup failed.
Do you want to enable a Automatic check for Continuity each boot?

Steps done to try to fix the issue: Ran multiple times.

I have the entire text file with the bazillion lines if you need to see it.

**Comment by drgonz0** [comment]
So just running the tool worked once you had SIP disabled?

**Comment by checkolala** [comment]
@drgonz0 : yes, works for me

**Comment by demeeder** [comment]
yes.  Back to requiring SIP being disabled.  Everything worked as before.

**Comment by drgonz0** [comment]
With your success I felt comfortable upgrading.  I didn't have to do anything and all Handoff and Continuity items are working.  I have a Mid 2010 27" iMac i7.  About 2 or 3 years ago I upgraded the wifi/bluetooth module.  So I'm working out of the box without any need for disabling SIP, or running Continuity activation tool.

**Comment by skill83** [comment]
For me is not working on MBP2011@i7-2720QM@2.20GHz with a BCM94331PCIEBT4CAX wifi card.

**Comment by Squuiid** [comment]
Also not working for me on a clean install of macOS High Sierra 10.13 on a Mac Pro 5,1, using a Broadcom BCM943602CDP.
When running CAT for the first time it says that Continuity is already activated and then quits.

**Comment by seanhoyt** [comment]
Also not working here, with the exception of AirDrop (no Handoff, Instant Hotspot, Universal Clipboard, etc.). Clean install of 10.13 on a Late 2011 MBP (MacBookPro8,2) with a BCM94331PCIEBT4CAX card. Worked under El Capitan and Sierra with no issues.

**Comment by sysfloat** [comment]
fixed in the latest beta.
