### ISSUE TITLE
Handoff stopped working on Mac Pro 5,1 with BCM94360CD after 10.12.6 update

### ISSUE THREAD

**Issue by sparky672** [dokterdok/Continuity-Activation-Tool#411]
2012 Mac Pro 5,1 with the upgraded internal wireless card (BCM94360CD + adapter).

Everything was working fine for about a year, all Handoff and Continuity; until the last Sierra update (10.12.6), and now Handoff is dead.  I am not using CAT because[ according to the chart](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility#airport-extreme-card-upgrades), no software patch is required with the BCM94360CD + adapter.  CAT's "system compatibility" is showing "OK" for everything and Continuity as "active".  I'm also seeing the Handoff checkbox checked in General settings.

Anyway, it's broken now and tried all of the usual logging in/out of iCloud on all devices, etc.  Nothing working to get Handoff going again.  Only Handoff and Hotspot broken.  Continuity (SMS forwarding & cellular calls) and Airdrop are still working fine.

Any suggestions appreciated.

**EDIT**: It's being reported to me [in another thread](https://github.com/dokterdok/Continuity-Activation-Tool/issues/397#issuecomment-346121357), that 10.12.6 broke Handoff despite any upgraded wireless card... CAT is required now.  I will post an update when I finally figure this out.

**EDIT 2:  Working again!**

I had to run CAT via command line with a `-f` in order to force it to skip the checks.  Otherwise, CAT would do nothing since it thinks Continuity is already active.

To `cd` into the CAT app, I simply typed `cd` and dragged/dropped the CAT application<sup>1</sup> into the Terminal window...

`Mac-Pro:~ username$ cd /Applications/Utilities/Continuity\ Activation\ Tool.app/Contents/Resources/`

Then I tried to run the `sudo contitool.sh -f` command...

`Mac-Pro:Resources username$ sudo contitool.sh -f`

I then got this error...

`sudo: contitool.sh: command not found`

So I had to run this command instead:

`sudo ./contitool.sh -f`

Then I logged out of iCloud, rebooted (_zapped PRAM during reboot<sup>2</sup>_), and logged back into iCloud.

<sup>1</sup> CAT version 2.6b6
<sup>2</sup> hold command-option-P-R during boot... listen for startup chime a couple/few times.

**Comment by rkamranb** [comment]
Can anyone help?
I was at mac os high sierra 10.13.6 and handoff was working perfectly after using the CAT,
But later on i had some performance issues with mac os so i made a back up and i have installed a fresh and clean mac os high sierra 10.13.6 i have again used the same CAT so airdrop works, iphone forwards the cellular calls to mac, messages are bein forwarded to mac as well but hand off is not working, i have tried everything many times like sign out from icloud on both devices, enable/disable SIP bluetooth/ Wifi switched on and off, handoff option switched on and off on both devices but handoff does not work.

I decided to boot from the backup hardrive and tested continuity and airdrop it works fine on that

Is there a way i can copy my airdop and continuity setting from my backup hard disk and replace it on my new setup?
