### ISSUE TITLE
Handoff not working on Mac Pro 4,1 (5,1 flash) with Broadcom card in High Sierra 10.13.2 after forcing CAT mod

### ISSUE THREAD

**Issue by GGitR** [dokterdok/Continuity-Activation-Tool#418]
Have you tried [these steps](https://github.com/dokterdok/Continuity-Activation-Tool/wiki#cant-open-the-tool)?

Yes

Is there already an open topic for this issue?

I don't believe so.

Please include the following information.

- OS Version: 10.13.2
- Mac model: "Early 2009" 4,1 (flashed to 5,1)
- Dongle or replaced card?: Replaced card
- Used dongle/card: Broadcom BCM43xx 1.0 (7.77.37.5.1a3)

Your Issue:

I came across this tool a few years back and ran it. It worked! In fact, Handoff and Universal Clipboard had been working well for a long time...then I upgraded to High Sierra, and both stopped working.

I ran the verification check just to make sure, and it told me:

Verifying OS X version...               Warning: This tool wasn't tested with OS X versions higher than 10.10. Detected OS version: 10.13.2
Verifying Wi-Fi hardware...             WARNING. An unknown/untested AirPort card using the 'BrcmNIC' kext is active. This tool can't fix this.

However, everything appears to be reported as working:

WIFI
AirDrop: Supported
Auto Unlock: Supported

BLUETOOTH
Bluetooth Low Energy Supported: Yes
Handoff Supported: Yes
Instant Hot Spot Supported: Yes
Manufacturer: Broadcom
Transport: USB
Chipset:	20702B0
Firmware Version:	v143 c9282
Bluetooth Power: On
Discoverable:	Off
Connectable:	Yes
Auto Seek Pointing: On
Remote wake: On
Apple Bluetooth Software Version: 6.0.2f2

Bluetooth magic keyboard and trackpad continue to work perfectly.

Handoff works between my iPad Air 2 and iPhone 7 (both running iOS 11) and with my MacBook Pro Retina "Mid 2012"

So I decided to force it...

Steps done to try to fix the issue:
1.) Downloaded the latest CAT
2.) Disabled SIP
3.) Ran sudo ./contitool.sh -f (at the end, when asked if I "want to enable a Automatic check for Continuity each boot," I selected NO)
4.) Rebooted (everything came back properly, no graphics issues, hangs, etc.)
5.) Logged out of iCloud on my Mac Pro (then logged back in)
6.) Turned off Handoff on all devices (then turned it back on)

Handoff is still not working after all this.

**Comment by sparky672** [comment]
>  1.) Downloaded the latest CAT

Which branch of CAT did you use?  FYI - there is a "beta" branch for Sierra and High Sierra.

>  5.) Logged out of iCloud on my Mac Pro (then logged back in)

After I upgraded my wireless card last year, I couldn't get Handoff to work, no matter what I tried, and it went on for days.  Finally discovered the trick is that you have to reboot *after* logging out of iCloud, but *before* you log back into iCloud.  In other words, reboot between logging out/in to iCloud.  _For good measure, I zapped the PRAM (command-option-P-R) during that reboot too._  

Even then, you may have to wait a minute or two after logging back into to iCloud.  (Apple needs a Handoff troubleshooting assistant or a better way to verify/activate within iCloud.)

**Comment by GGitR** [comment]
1.) I used the main branch. I did not dig into the beta branches. I will download the High Sierra one now and try it.
2.) I did just try to log out of iCloud, shut down, PRAM reset, and log back in, but to no avail.

**Comment by sparky672** [comment]
Well, that's your problem.  **Must** use beta for Sierra and High Sierra.

**Comment by GGitR** [comment]
Got it. So I just downloaded 2.6b6, and I am running it. When I choose option 1, it tells me Continuity is already active and asks me to reboot. I rebooted, and now Continuity is working! God bless you guys! You're amazing!!! Thanks for all the help!!

**Comment by sparky672** [comment]
No.  You'll have to use the terminal to force CAT to bypass the check.

See my last edit here:

https://github.com/dokterdok/Continuity-Activation-Tool/issues/411#issue-271333251

**Comment by GGitR** [comment]
I was wondering about that, but apparently I rebooted as it said, and it worked! Thanks again!

**Comment by sparky672** [comment]
Okay, great.... so many different scenarios.  Hard to keep track, especially when the compatibility chart was broken by Sierra 10.12.6 and High Sierra.  It might have been a simple case of CAT's kext cache dump got it unstuck.

**Comment by rkamranb** [comment]
Can anyone help?
I was at mac os high sierra 10.13.6 and handoff was working perfectly after using the CAT, 
But later on i had some performance issues with mac os so i made a back up and i have installed a fresh and clean mac os high sierra 10.13.6 i have again used the same CAT so airdrop works, iphone forwards the cellular calls to mac, messages are bein forwarded to mac as well but hand off is not working, i have tried everything many times like sign out from icloud on both devices, enable/disable SIP bluetooth/ Wifi switched on and off, handoff option switched on and off on both devices but handoff does not work.

I decided to boot from the backup hardrive and tested continuity and airdrop it works fine on that 

Is there a way i can copy my airdop and continuity setting from my backup hard disk and replace it on my new setup?

**Comment by sparky672** [comment]
Did you reboot in between signing out of iCloud and signing back in?  Rebooting was always s critical step for me.

**Comment by rkamranb** [comment]
@sparky672 thanks for that it works now as i was not rebooting after icloud signing out i was signing in straight away. thanks again its sorted
