### ISSUE TITLE
Bluetooth dropping connection issue

### ISSUE THREAD

**Issue by smwoodward** [dokterdok/Continuity-Activation-Tool#88]
I noticed this after Yosemite came out.  I have the the GBU521 USB dongle, and it keeps dropping the 4.0 connection.  I can watch the icon on the menu bar showing a connection then dropping it.  I have a 15" 2008 Macbook pro.  Any help would be great.

**Comment by AhmedOsama** [comment]
any fixes or updates ?! As I am still facing the exact same issue
