### ISSUE TITLE
Iogear GBU521 dongle mouse connection issue

### ISSUE THREAD

**Issue by michaeltilst** [dokterdok/Continuity-Activation-Tool#97]
Hi @dokterdok 

I have a iMac 2011 (mid)

I bought the Iogear GBU521 dongle and used the Continuity Activation tool 2.0.
I had some issues when CAT didn't detect my dongle until I disabled the native BT card (using a wired mouse to avoid the system warning).

Anway - CAT detected the dongle and run the processes as it should. After reboot 
everything seemed perfect in "about this mac -> system information" (see screenshot)
EXCEPT that my magic mouse/trackpad didn't work anymore.
I tried everything to reconnect the mouse to the "new" bluetooth connection (the dongle instead of the onboard card). Pressing OPTION+bluetooth icon in menubar confirmed that the dongles bluetooth connection was active.

Tried to "uninstall" in CAT but mouse/keypad still didn't work after reboot. 
Restored the "iobluetoothfamily.kext" via timemachine and managed to change active BT-card to the original BT-card. And magic mouse/keypad was working again.

Do you have a solution for the lost connection to my mouse/keypad? 

Looking forward to hear from you :-)

Michael

![screenshot](https://cloud.githubusercontent.com/assets/9915130/5513075/7a20291e-87e7-11e4-9ed8-a057ac839222.jpg)

System diag., when the dongle is inserted but internal BT-card is active:

--- OS X Continuity Activation Tool 2.0.0 ---
                 by dokterdok                 

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: iMac12,1
Verifying Mac board-id...               OK. Long board id detected: Mac-942B5BF58194151B
Verifying OS X version...               OK. Mac OS X 10.10.1 (14B25) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=4, expected 6.
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v208 c518

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in

Press any key to go back to the main menu...

When IoGear dongle is active, the diag. looks like this:

--- OS X Continuity Activation Tool 2.0.0 ---
                 by dokterdok                 

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: iMac12,1
Verifying Mac board-id...               OK. Long board id detected: Mac-942B5BF58194151B
Verifying OS X version...               OK. Mac OS X 10.10.1 (14B25) detected
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and is using the Continuity compatible Brcm4360 kext
Verifying AWDL status...                OK. An AWDL interface is up, Wi-Fi is ready for Continuity
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v14 c4096

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Bluetooth blacklist status... OK. Your Mac model is not blacklisted
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in

Press any key to go back to the main menu...

**Comment by JCBerger** [comment]
@michaeltilst Did you have to do anything special for the mouse to be found? I'm in the "settings->Mouse" part, but it just keeps searching with "No mouse found."
